//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.14 at 03:13:03 PM PDT 
//


package net.sourceforge.seqware.queryengine.webservice.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sourceforge.seqware.queryengine.webservice.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EXPERIMENT_QNAME = new QName("", "EXPERIMENT");
    private final static QName _SAMPLE_QNAME = new QName("", "SAMPLE");
    private final static QName _RUN_QNAME = new QName("", "RUN");
    private final static QName _ANALYSIS_QNAME = new QName("", "ANALYSIS");
    private final static QName _SUBMISSION_QNAME = new QName("", "SUBMISSION");
    private final static QName _STUDY_QNAME = new QName("", "STUDY");
    private final static QName _StudyTypeDESCRIPTORSTUDYABSTRACT_QNAME = new QName("", "STUDY_ABSTRACT");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sourceforge.seqware.queryengine.webservice.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC }
     * 
     */
    public ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC createExperimentTypeDESIGNSPOTDESCRIPTORSPOTDECODESPEC() {
        return new ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC();
    }

    /**
     * Create an instance of {@link ExperimentSet }
     * 
     */
    public ExperimentSet createEXPERIMENTSET() {
        return new ExperimentSet();
    }

    /**
     * Create an instance of {@link AnalysisType.PARENT.EXPERIMENTREF }
     * 
     */
    public AnalysisType.PARENT.EXPERIMENTREF createAnalysisTypePARENTEXPERIMENTREF() {
        return new AnalysisType.PARENT.EXPERIMENTREF();
    }

    /**
     * Create an instance of {@link SubmissionType.CONTACTS.CONTACT }
     * 
     */
    public SubmissionType.CONTACTS.CONTACT createSubmissionTypeCONTACTSCONTACT() {
        return new SubmissionType.CONTACTS.CONTACT();
    }

    /**
     * Create an instance of {@link ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC.READSPEC }
     * 
     */
    public ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC.READSPEC createExperimentTypeDESIGNSPOTDESCRIPTORSPOTDECODESPECREADSPEC() {
        return new ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC.READSPEC();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.VALIDATE }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.VALIDATE createSubmissionTypeACTIONSACTIONVALIDATE() {
        return new SubmissionType.ACTIONS.ACTION.VALIDATE();
    }

    /**
     * Create an instance of {@link RunType.DATABLOCK }
     * 
     */
    public RunType.DATABLOCK createRunTypeDATABLOCK() {
        return new RunType.DATABLOCK();
    }

    /**
     * Create an instance of {@link ExperimentType.PLATFORM.ILLUMINA }
     * 
     */
    public ExperimentType.PLATFORM.ILLUMINA createExperimentTypePLATFORMILLUMINA() {
        return new ExperimentType.PLATFORM.ILLUMINA();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.MODIFY }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.MODIFY createSubmissionTypeACTIONSACTIONMODIFY() {
        return new SubmissionType.ACTIONS.ACTION.MODIFY();
    }

    /**
     * Create an instance of {@link RunType.RUNLINKS.RUNLINK }
     * 
     */
    public RunType.RUNLINKS.RUNLINK createRunTypeRUNLINKSRUNLINK() {
        return new RunType.RUNLINKS.RUNLINK();
    }

    /**
     * Create an instance of {@link RunType.DATABLOCK.FILES }
     * 
     */
    public RunType.DATABLOCK.FILES createRunTypeDATABLOCKFILES() {
        return new RunType.DATABLOCK.FILES();
    }

    /**
     * Create an instance of {@link ExperimentType.STUDYREF }
     * 
     */
    public ExperimentType.STUDYREF createExperimentTypeSTUDYREF() {
        return new ExperimentType.STUDYREF();
    }

    /**
     * Create an instance of {@link AnalysisType.PARENT.SAMPLEPOOLREF }
     * 
     */
    public AnalysisType.PARENT.SAMPLEPOOLREF createAnalysisTypePARENTSAMPLEPOOLREF() {
        return new AnalysisType.PARENT.SAMPLEPOOLREF();
    }

    /**
     * Create an instance of {@link ExperimentType.PROCESSING.BASECALLS }
     * 
     */
    public ExperimentType.PROCESSING.BASECALLS createExperimentTypePROCESSINGBASECALLS() {
        return new ExperimentType.PROCESSING.BASECALLS();
    }

    /**
     * Create an instance of {@link ExperimentType.DESIGN }
     * 
     */
    public ExperimentType.DESIGN createExperimentTypeDESIGN() {
        return new ExperimentType.DESIGN();
    }

    /**
     * Create an instance of {@link RunType.EXPERIMENTREF }
     * 
     */
    public RunType.EXPERIMENTREF createRunTypeEXPERIMENTREF() {
        return new RunType.EXPERIMENTREF();
    }

    /**
     * Create an instance of {@link SampleSet }
     * 
     */
    public SampleSet createSAMPLESET() {
        return new SampleSet();
    }

    /**
     * Create an instance of {@link StudyType.STUDYATTRIBUTES }
     * 
     */
    public StudyType.STUDYATTRIBUTES createStudyTypeSTUDYATTRIBUTES() {
        return new StudyType.STUDYATTRIBUTES();
    }

    /**
     * Create an instance of {@link SampleType.MEMBERS }
     * 
     */
    public SampleType.MEMBERS createSampleTypeMEMBERS() {
        return new SampleType.MEMBERS();
    }

    /**
     * Create an instance of {@link SampleType.SAMPLEATTRIBUTES }
     * 
     */
    public SampleType.SAMPLEATTRIBUTES createSampleTypeSAMPLEATTRIBUTES() {
        return new SampleType.SAMPLEATTRIBUTES();
    }

    /**
     * Create an instance of {@link ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT }
     * 
     */
    public ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT createExperimentTypeDESIGNLIBRARYDESCRIPTORLIBRARYLAYOUT() {
        return new ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT();
    }

    /**
     * Create an instance of {@link AnalysisType.PARENT.STUDYREF }
     * 
     */
    public AnalysisType.PARENT.STUDYREF createAnalysisTypePARENTSTUDYREF() {
        return new AnalysisType.PARENT.STUDYREF();
    }

    /**
     * Create an instance of {@link SubmissionSet }
     * 
     */
    public SubmissionSet createSUBMISSIONSET() {
        return new SubmissionSet();
    }

    /**
     * Create an instance of {@link AnalysisType.PARENT.RUNREF }
     * 
     */
    public AnalysisType.PARENT.RUNREF createAnalysisTypePARENTRUNREF() {
        return new AnalysisType.PARENT.RUNREF();
    }

    /**
     * Create an instance of {@link AnalysisType }
     * 
     */
    public AnalysisType createAnalysisType() {
        return new AnalysisType();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISFILES.FILE }
     * 
     */
    public AnalysisType.ANALYSISFILES.FILE createAnalysisTypeANALYSISFILESFILE() {
        return new AnalysisType.ANALYSISFILES.FILE();
    }

    /**
     * Create an instance of {@link ExperimentType.EXPERIMENTLINKS }
     * 
     */
    public ExperimentType.EXPERIMENTLINKS createExperimentTypeEXPERIMENTLINKS() {
        return new ExperimentType.EXPERIMENTLINKS();
    }

    /**
     * Create an instance of {@link StudyType }
     * 
     */
    public StudyType createStudyType() {
        return new StudyType();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISLINKS.ANALYSISLINK.URLLINK }
     * 
     */
    public AnalysisType.ANALYSISLINKS.ANALYSISLINK.URLLINK createAnalysisTypeANALYSISLINKSANALYSISLINKURLLINK() {
        return new AnalysisType.ANALYSISLINKS.ANALYSISLINK.URLLINK();
    }

    /**
     * Create an instance of {@link SampleType.SAMPLELINKS }
     * 
     */
    public SampleType.SAMPLELINKS createSampleTypeSAMPLELINKS() {
        return new SampleType.SAMPLELINKS();
    }

    /**
     * Create an instance of {@link AnalysisType.PARENT.SAMPLEREF }
     * 
     */
    public AnalysisType.PARENT.SAMPLEREF createAnalysisTypePARENTSAMPLEREF() {
        return new AnalysisType.PARENT.SAMPLEREF();
    }

    /**
     * Create an instance of {@link StudySet }
     * 
     */
    public StudySet createSTUDYSET() {
        return new StudySet();
    }

    /**
     * Create an instance of {@link ExperimentType.PROCESSING.QUALITYSCORES }
     * 
     */
    public ExperimentType.PROCESSING.QUALITYSCORES createExperimentTypePROCESSINGQUALITYSCORES() {
        return new ExperimentType.PROCESSING.QUALITYSCORES();
    }

    /**
     * Create an instance of {@link SampleType.SAMPLELINKS.SAMPLELINK }
     * 
     */
    public SampleType.SAMPLELINKS.SAMPLELINK createSampleTypeSAMPLELINKSSAMPLELINK() {
        return new SampleType.SAMPLELINKS.SAMPLELINK();
    }

    /**
     * Create an instance of {@link RunType.RUNLINKS.RUNLINK.URLLINK }
     * 
     */
    public RunType.RUNLINKS.RUNLINK.URLLINK createRunTypeRUNLINKSRUNLINKURLLINK() {
        return new RunType.RUNLINKS.RUNLINK.URLLINK();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISATTRIBUTES.ANALYSISATTRIBUTE }
     * 
     */
    public AnalysisType.ANALYSISATTRIBUTES.ANALYSISATTRIBUTE createAnalysisTypeANALYSISATTRIBUTESANALYSISATTRIBUTE() {
        return new AnalysisType.ANALYSISATTRIBUTES.ANALYSISATTRIBUTE();
    }

    /**
     * Create an instance of {@link AnalysisType.PARENT }
     * 
     */
    public AnalysisType.PARENT createAnalysisTypePARENT() {
        return new AnalysisType.PARENT();
    }

    /**
     * Create an instance of {@link SampleType.MEMBERS.MEMBER }
     * 
     */
    public SampleType.MEMBERS.MEMBER createSampleTypeMEMBERSMEMBER() {
        return new SampleType.MEMBERS.MEMBER();
    }

    /**
     * Create an instance of {@link SampleType.SAMPLEATTRIBUTES.SAMPLEATTRIBUTE }
     * 
     */
    public SampleType.SAMPLEATTRIBUTES.SAMPLEATTRIBUTE createSampleTypeSAMPLEATTRIBUTESSAMPLEATTRIBUTE() {
        return new SampleType.SAMPLEATTRIBUTES.SAMPLEATTRIBUTE();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISTYPE }
     * 
     */
    public AnalysisType.ANALYSISTYPE createAnalysisTypeANALYSISTYPE() {
        return new AnalysisType.ANALYSISTYPE();
    }

    /**
     * Create an instance of {@link SampleType.SAMPLELINKS.SAMPLELINK.ENTREZLINK }
     * 
     */
    public SampleType.SAMPLELINKS.SAMPLELINK.ENTREZLINK createSampleTypeSAMPLELINKSSAMPLELINKENTREZLINK() {
        return new SampleType.SAMPLELINKS.SAMPLELINK.ENTREZLINK();
    }

    /**
     * Create an instance of {@link SampleType.SAMPLENAME }
     * 
     */
    public SampleType.SAMPLENAME createSampleTypeSAMPLENAME() {
        return new SampleType.SAMPLENAME();
    }

    /**
     * Create an instance of {@link RunSet }
     * 
     */
    public RunSet createRUNSET() {
        return new RunSet();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISFILES }
     * 
     */
    public AnalysisType.ANALYSISFILES createAnalysisTypeANALYSISFILES() {
        return new AnalysisType.ANALYSISFILES();
    }

    /**
     * Create an instance of {@link ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.URLLINK }
     * 
     */
    public ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.URLLINK createExperimentTypeEXPERIMENTLINKSEXPERIMENTLINKURLLINK() {
        return new ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.URLLINK();
    }

    /**
     * Create an instance of {@link StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK }
     * 
     */
    public StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK createStudyTypeSTUDYLINKSSTUDYLINKENTREZLINK() {
        return new StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK();
    }

    /**
     * Create an instance of {@link ExperimentType.DESIGN.LIBRARYDESCRIPTOR }
     * 
     */
    public ExperimentType.DESIGN.LIBRARYDESCRIPTOR createExperimentTypeDESIGNLIBRARYDESCRIPTOR() {
        return new ExperimentType.DESIGN.LIBRARYDESCRIPTOR();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISLINKS.ANALYSISLINK.XREFLINK }
     * 
     */
    public AnalysisType.ANALYSISLINKS.ANALYSISLINK.XREFLINK createAnalysisTypeANALYSISLINKSANALYSISLINKXREFLINK() {
        return new AnalysisType.ANALYSISLINKS.ANALYSISLINK.XREFLINK();
    }

    /**
     * Create an instance of {@link ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.ENTREZLINK }
     * 
     */
    public ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.ENTREZLINK createExperimentTypeEXPERIMENTLINKSEXPERIMENTLINKENTREZLINK() {
        return new ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.ENTREZLINK();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISLINKS.ANALYSISLINK }
     * 
     */
    public AnalysisType.ANALYSISLINKS.ANALYSISLINK createAnalysisTypeANALYSISLINKSANALYSISLINK() {
        return new AnalysisType.ANALYSISLINKS.ANALYSISLINK();
    }

    /**
     * Create an instance of {@link SubmissionType }
     * 
     */
    public SubmissionType createSubmissionType() {
        return new SubmissionType();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS }
     * 
     */
    public SubmissionType.ACTIONS createSubmissionTypeACTIONS() {
        return new SubmissionType.ACTIONS();
    }

    /**
     * Create an instance of {@link ExperimentType.PLATFORM.LS454 }
     * 
     */
    public ExperimentType.PLATFORM.LS454 createExperimentTypePLATFORMLS454() {
        return new ExperimentType.PLATFORM.LS454();
    }

    /**
     * Create an instance of {@link ExperimentType.PLATFORM.ABISOLID.COLORMATRIX.COLOR }
     * 
     */
    public ExperimentType.PLATFORM.ABISOLID.COLORMATRIX.COLOR createExperimentTypePLATFORMABISOLIDCOLORMATRIXCOLOR() {
        return new ExperimentType.PLATFORM.ABISOLID.COLORMATRIX.COLOR();
    }

    /**
     * Create an instance of {@link ExperimentType.PLATFORM }
     * 
     */
    public ExperimentType.PLATFORM createExperimentTypePLATFORM() {
        return new ExperimentType.PLATFORM();
    }

    /**
     * Create an instance of {@link ExperimentType.DESIGN.SAMPLEDESCRIPTOR }
     * 
     */
    public ExperimentType.DESIGN.SAMPLEDESCRIPTOR createExperimentTypeDESIGNSAMPLEDESCRIPTOR() {
        return new ExperimentType.DESIGN.SAMPLEDESCRIPTOR();
    }

    /**
     * Create an instance of {@link StudyType.DESCRIPTOR }
     * 
     */
    public StudyType.DESCRIPTOR createStudyTypeDESCRIPTOR() {
        return new StudyType.DESCRIPTOR();
    }

    /**
     * Create an instance of {@link AnalysisType.PARENT.SAMPLEPOOLREF.MEMBER }
     * 
     */
    public AnalysisType.PARENT.SAMPLEPOOLREF.MEMBER createAnalysisTypePARENTSAMPLEPOOLREFMEMBER() {
        return new AnalysisType.PARENT.SAMPLEPOOLREF.MEMBER();
    }

    /**
     * Create an instance of {@link StudyType.STUDYLINKS }
     * 
     */
    public StudyType.STUDYLINKS createStudyTypeSTUDYLINKS() {
        return new StudyType.STUDYLINKS();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION }
     * 
     */
    public SubmissionType.ACTIONS.ACTION createSubmissionTypeACTIONSACTION() {
        return new SubmissionType.ACTIONS.ACTION();
    }

    /**
     * Create an instance of {@link ExperimentType.EXPERIMENTATTRIBUTES }
     * 
     */
    public ExperimentType.EXPERIMENTATTRIBUTES createExperimentTypeEXPERIMENTATTRIBUTES() {
        return new ExperimentType.EXPERIMENTATTRIBUTES();
    }

    /**
     * Create an instance of {@link SubmissionType.CONTACTS }
     * 
     */
    public SubmissionType.CONTACTS createSubmissionTypeCONTACTS() {
        return new SubmissionType.CONTACTS();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.SUPPRESS }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.SUPPRESS createSubmissionTypeACTIONSACTIONSUPPRESS() {
        return new SubmissionType.ACTIONS.ACTION.SUPPRESS();
    }

    /**
     * Create an instance of {@link ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT.PAIRED }
     * 
     */
    public ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT.PAIRED createExperimentTypeDESIGNLIBRARYDESCRIPTORLIBRARYLAYOUTPAIRED() {
        return new ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT.PAIRED();
    }

    /**
     * Create an instance of {@link SubmissionType.FILES }
     * 
     */
    public SubmissionType.FILES createSubmissionTypeFILES() {
        return new SubmissionType.FILES();
    }

    /**
     * Create an instance of {@link ExperimentType.PLATFORM.ABISOLID }
     * 
     */
    public ExperimentType.PLATFORM.ABISOLID createExperimentTypePLATFORMABISOLID() {
        return new ExperimentType.PLATFORM.ABISOLID();
    }

    /**
     * Create an instance of {@link AnalysisSet }
     * 
     */
    public AnalysisSet createANALYSISSET() {
        return new AnalysisSet();
    }

    /**
     * Create an instance of {@link SampleType }
     * 
     */
    public SampleType createSampleType() {
        return new SampleType();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISATTRIBUTES }
     * 
     */
    public AnalysisType.ANALYSISATTRIBUTES createAnalysisTypeANALYSISATTRIBUTES() {
        return new AnalysisType.ANALYSISATTRIBUTES();
    }

    /**
     * Create an instance of {@link RunType.RUNATTRIBUTES }
     * 
     */
    public RunType.RUNATTRIBUTES createRunTypeRUNATTRIBUTES() {
        return new RunType.RUNATTRIBUTES();
    }

    /**
     * Create an instance of {@link ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK }
     * 
     */
    public ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK createExperimentTypeEXPERIMENTLINKSEXPERIMENTLINK() {
        return new ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK();
    }

    /**
     * Create an instance of {@link ExperimentType.DESIGN.SPOTDESCRIPTOR }
     * 
     */
    public ExperimentType.DESIGN.SPOTDESCRIPTOR createExperimentTypeDESIGNSPOTDESCRIPTOR() {
        return new ExperimentType.DESIGN.SPOTDESCRIPTOR();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.ADD }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.ADD createSubmissionTypeACTIONSACTIONADD() {
        return new SubmissionType.ACTIONS.ACTION.ADD();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISLINKS.ANALYSISLINK.ENTREZLINK }
     * 
     */
    public AnalysisType.ANALYSISLINKS.ANALYSISLINK.ENTREZLINK createAnalysisTypeANALYSISLINKSANALYSISLINKENTREZLINK() {
        return new AnalysisType.ANALYSISLINKS.ANALYSISLINK.ENTREZLINK();
    }

    /**
     * Create an instance of {@link SampleType.SAMPLELINKS.SAMPLELINK.URLLINK }
     * 
     */
    public SampleType.SAMPLELINKS.SAMPLELINK.URLLINK createSampleTypeSAMPLELINKSSAMPLELINKURLLINK() {
        return new SampleType.SAMPLELINKS.SAMPLELINK.URLLINK();
    }

    /**
     * Create an instance of {@link SubmissionType.FILES.FILE }
     * 
     */
    public SubmissionType.FILES.FILE createSubmissionTypeFILESFILE() {
        return new SubmissionType.FILES.FILE();
    }

    /**
     * Create an instance of {@link ExperimentType.EXPERIMENTATTRIBUTES.EXPERIMENTATTRIBUTE }
     * 
     */
    public ExperimentType.EXPERIMENTATTRIBUTES.EXPERIMENTATTRIBUTE createExperimentTypeEXPERIMENTATTRIBUTESEXPERIMENTATTRIBUTE() {
        return new ExperimentType.EXPERIMENTATTRIBUTES.EXPERIMENTATTRIBUTE();
    }

    /**
     * Create an instance of {@link RunType.DATABLOCK.FILES.FILE }
     * 
     */
    public RunType.DATABLOCK.FILES.FILE createRunTypeDATABLOCKFILESFILE() {
        return new RunType.DATABLOCK.FILES.FILE();
    }

    /**
     * Create an instance of {@link RunType.RUNLINKS.RUNLINK.ENTREZLINK }
     * 
     */
    public RunType.RUNLINKS.RUNLINK.ENTREZLINK createRunTypeRUNLINKSRUNLINKENTREZLINK() {
        return new RunType.RUNLINKS.RUNLINK.ENTREZLINK();
    }

    /**
     * Create an instance of {@link RunType.RUNATTRIBUTES.RUNATTRIBUTE }
     * 
     */
    public RunType.RUNATTRIBUTES.RUNATTRIBUTE createRunTypeRUNATTRIBUTESRUNATTRIBUTE() {
        return new RunType.RUNATTRIBUTES.RUNATTRIBUTE();
    }

    /**
     * Create an instance of {@link ExperimentType.PLATFORM.ABISOLID.COLORMATRIX }
     * 
     */
    public ExperimentType.PLATFORM.ABISOLID.COLORMATRIX createExperimentTypePLATFORMABISOLIDCOLORMATRIX() {
        return new ExperimentType.PLATFORM.ABISOLID.COLORMATRIX();
    }

    /**
     * Create an instance of {@link RunType.RUNLINKS }
     * 
     */
    public RunType.RUNLINKS createRunTypeRUNLINKS() {
        return new RunType.RUNLINKS();
    }

    /**
     * Create an instance of {@link ExperimentType }
     * 
     */
    public ExperimentType createExperimentType() {
        return new ExperimentType();
    }

    /**
     * Create an instance of {@link StudyType.STUDYLINKS.STUDYLINK.URLLINK }
     * 
     */
    public StudyType.STUDYLINKS.STUDYLINK.URLLINK createStudyTypeSTUDYLINKSSTUDYLINKURLLINK() {
        return new StudyType.STUDYLINKS.STUDYLINK.URLLINK();
    }

    /**
     * Create an instance of {@link StudyType.STUDYLINKS.STUDYLINK }
     * 
     */
    public StudyType.STUDYLINKS.STUDYLINK createStudyTypeSTUDYLINKSSTUDYLINK() {
        return new StudyType.STUDYLINKS.STUDYLINK();
    }

    /**
     * Create an instance of {@link ExperimentType.PLATFORM.HELICOS }
     * 
     */
    public ExperimentType.PLATFORM.HELICOS createExperimentTypePLATFORMHELICOS() {
        return new ExperimentType.PLATFORM.HELICOS();
    }

    /**
     * Create an instance of {@link StudyType.DESCRIPTOR.STUDYTYPE }
     * 
     */
    public StudyType.DESCRIPTOR.STUDYTYPE createStudyTypeDESCRIPTORSTUDYTYPE() {
        return new StudyType.DESCRIPTOR.STUDYTYPE();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.HOLD }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.HOLD createSubmissionTypeACTIONSACTIONHOLD() {
        return new SubmissionType.ACTIONS.ACTION.HOLD();
    }

    /**
     * Create an instance of {@link ExperimentType.PROCESSING }
     * 
     */
    public ExperimentType.PROCESSING createExperimentTypePROCESSING() {
        return new ExperimentType.PROCESSING();
    }

    /**
     * Create an instance of {@link RunType }
     * 
     */
    public RunType createRunType() {
        return new RunType();
    }

    /**
     * Create an instance of {@link AnalysisType.ANALYSISLINKS }
     * 
     */
    public AnalysisType.ANALYSISLINKS createAnalysisTypeANALYSISLINKS() {
        return new AnalysisType.ANALYSISLINKS();
    }

    /**
     * Create an instance of {@link StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE }
     * 
     */
    public StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE createStudyTypeSTUDYATTRIBUTESSTUDYATTRIBUTE() {
        return new StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE();
    }

    /**
     * Create an instance of {@link SubmissionType.ACTIONS.ACTION.RELEASE }
     * 
     */
    public SubmissionType.ACTIONS.ACTION.RELEASE createSubmissionTypeACTIONSACTIONRELEASE() {
        return new SubmissionType.ACTIONS.ACTION.RELEASE();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExperimentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXPERIMENT")
    public JAXBElement<ExperimentType> createEXPERIMENT(ExperimentType value) {
        return new JAXBElement<ExperimentType>(_EXPERIMENT_QNAME, ExperimentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SampleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SAMPLE")
    public JAXBElement<SampleType> createSAMPLE(SampleType value) {
        return new JAXBElement<SampleType>(_SAMPLE_QNAME, SampleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RunType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RUN")
    public JAXBElement<RunType> createRUN(RunType value) {
        return new JAXBElement<RunType>(_RUN_QNAME, RunType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnalysisType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ANALYSIS")
    public JAXBElement<AnalysisType> createANALYSIS(AnalysisType value) {
        return new JAXBElement<AnalysisType>(_ANALYSIS_QNAME, AnalysisType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmissionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SUBMISSION")
    public JAXBElement<SubmissionType> createSUBMISSION(SubmissionType value) {
        return new JAXBElement<SubmissionType>(_SUBMISSION_QNAME, SubmissionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StudyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STUDY")
    public JAXBElement<StudyType> createSTUDY(StudyType value) {
        return new JAXBElement<StudyType>(_STUDY_QNAME, StudyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STUDY_ABSTRACT", scope = StudyType.DESCRIPTOR.class)
    public JAXBElement<String> createStudyTypeDESCRIPTORSTUDYABSTRACT(String value) {
        return new JAXBElement<String>(_StudyTypeDESCRIPTORSTUDYABSTRACT_QNAME, String.class, StudyType.DESCRIPTOR.class, value);
    }

}
