//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.14 at 03:13:03 PM PDT 
//


package net.sourceforge.seqware.queryengine.webservice.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the net.sourceforge.seqware.queryengine.webservice.model package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 * @author morgantaschuk
 * @version $Id: $Id
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EXPERIMENT_QNAME = new QName("", "EXPERIMENT");
    private final static QName _SAMPLE_QNAME = new QName("", "SAMPLE");
    private final static QName _RUN_QNAME = new QName("", "RUN");
    private final static QName _ANALYSIS_QNAME = new QName("", "ANALYSIS");
    private final static QName _SUBMISSION_QNAME = new QName("", "SUBMISSION");
    private final static QName _STUDY_QNAME = new QName("", "STUDY");
    private final static QName _StudyTypeDESCRIPTORSTUDYABSTRACT_QNAME = new QName("", "STUDY_ABSTRACT");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sourceforge.seqware.queryengine.webservice.model
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC} object.
     */
    public ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC createExperimentTypeDESIGNSPOTDESCRIPTORSPOTDECODESPEC() {
        return new ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentSet}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentSet} object.
     */
    public ExperimentSet createEXPERIMENTSET() {
        return new ExperimentSet();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.EXPERIMENTREF}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.EXPERIMENTREF} object.
     */
    public AnalysisType.PARENT.EXPERIMENTREF createAnalysisTypePARENTEXPERIMENTREF() {
        return new AnalysisType.PARENT.EXPERIMENTREF();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.CONTACTS.CONTACT}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.CONTACTS.CONTACT} object.
     */
    public SubmissionType.CONTACTS.CONTACT createSubmissionTypeCONTACTSCONTACT() {
        return new SubmissionType.CONTACTS.CONTACT();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC.READSPEC}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC.READSPEC} object.
     */
    public ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC.READSPEC createExperimentTypeDESIGNSPOTDESCRIPTORSPOTDECODESPECREADSPEC() {
        return new ExperimentType.DESIGN.SPOTDESCRIPTOR.SPOTDECODESPEC.READSPEC();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.VALIDATE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.VALIDATE} object.
     */
    public SubmissionType.ACTIONS.ACTION.VALIDATE createSubmissionTypeACTIONSACTIONVALIDATE() {
        return new SubmissionType.ACTIONS.ACTION.VALIDATE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.DATABLOCK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.DATABLOCK} object.
     */
    public RunType.DATABLOCK createRunTypeDATABLOCK() {
        return new RunType.DATABLOCK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.ILLUMINA}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.ILLUMINA} object.
     */
    public ExperimentType.PLATFORM.ILLUMINA createExperimentTypePLATFORMILLUMINA() {
        return new ExperimentType.PLATFORM.ILLUMINA();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.MODIFY}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.MODIFY} object.
     */
    public SubmissionType.ACTIONS.ACTION.MODIFY createSubmissionTypeACTIONSACTIONMODIFY() {
        return new SubmissionType.ACTIONS.ACTION.MODIFY();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNLINKS.RUNLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNLINKS.RUNLINK} object.
     */
    public RunType.RUNLINKS.RUNLINK createRunTypeRUNLINKSRUNLINK() {
        return new RunType.RUNLINKS.RUNLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.DATABLOCK.FILES}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.DATABLOCK.FILES} object.
     */
    public RunType.DATABLOCK.FILES createRunTypeDATABLOCKFILES() {
        return new RunType.DATABLOCK.FILES();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.STUDYREF}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.STUDYREF} object.
     */
    public ExperimentType.STUDYREF createExperimentTypeSTUDYREF() {
        return new ExperimentType.STUDYREF();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.SAMPLEPOOLREF}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.SAMPLEPOOLREF} object.
     */
    public AnalysisType.PARENT.SAMPLEPOOLREF createAnalysisTypePARENTSAMPLEPOOLREF() {
        return new AnalysisType.PARENT.SAMPLEPOOLREF();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PROCESSING.BASECALLS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PROCESSING.BASECALLS} object.
     */
    public ExperimentType.PROCESSING.BASECALLS createExperimentTypePROCESSINGBASECALLS() {
        return new ExperimentType.PROCESSING.BASECALLS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN} object.
     */
    public ExperimentType.DESIGN createExperimentTypeDESIGN() {
        return new ExperimentType.DESIGN();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.EXPERIMENTREF}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.EXPERIMENTREF} object.
     */
    public RunType.EXPERIMENTREF createRunTypeEXPERIMENTREF() {
        return new RunType.EXPERIMENTREF();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleSet}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleSet} object.
     */
    public SampleSet createSAMPLESET() {
        return new SampleSet();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYATTRIBUTES}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYATTRIBUTES} object.
     */
    public StudyType.STUDYATTRIBUTES createStudyTypeSTUDYATTRIBUTES() {
        return new StudyType.STUDYATTRIBUTES();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.MEMBERS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.MEMBERS} object.
     */
    public SampleType.MEMBERS createSampleTypeMEMBERS() {
        return new SampleType.MEMBERS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLEATTRIBUTES}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLEATTRIBUTES} object.
     */
    public SampleType.SAMPLEATTRIBUTES createSampleTypeSAMPLEATTRIBUTES() {
        return new SampleType.SAMPLEATTRIBUTES();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT} object.
     */
    public ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT createExperimentTypeDESIGNLIBRARYDESCRIPTORLIBRARYLAYOUT() {
        return new ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.STUDYREF}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.STUDYREF} object.
     */
    public AnalysisType.PARENT.STUDYREF createAnalysisTypePARENTSTUDYREF() {
        return new AnalysisType.PARENT.STUDYREF();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionSet}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionSet} object.
     */
    public SubmissionSet createSUBMISSIONSET() {
        return new SubmissionSet();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.RUNREF}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.RUNREF} object.
     */
    public AnalysisType.PARENT.RUNREF createAnalysisTypePARENTRUNREF() {
        return new AnalysisType.PARENT.RUNREF();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType} object.
     */
    public AnalysisType createAnalysisType() {
        return new AnalysisType();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISFILES.FILE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISFILES.FILE} object.
     */
    public AnalysisType.ANALYSISFILES.FILE createAnalysisTypeANALYSISFILESFILE() {
        return new AnalysisType.ANALYSISFILES.FILE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTLINKS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTLINKS} object.
     */
    public ExperimentType.EXPERIMENTLINKS createExperimentTypeEXPERIMENTLINKS() {
        return new ExperimentType.EXPERIMENTLINKS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType} object.
     */
    public StudyType createStudyType() {
        return new StudyType();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISLINKS.ANALYSISLINK.URLLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISLINKS.ANALYSISLINK.URLLINK} object.
     */
    public AnalysisType.ANALYSISLINKS.ANALYSISLINK.URLLINK createAnalysisTypeANALYSISLINKSANALYSISLINKURLLINK() {
        return new AnalysisType.ANALYSISLINKS.ANALYSISLINK.URLLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLELINKS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLELINKS} object.
     */
    public SampleType.SAMPLELINKS createSampleTypeSAMPLELINKS() {
        return new SampleType.SAMPLELINKS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.SAMPLEREF}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.SAMPLEREF} object.
     */
    public AnalysisType.PARENT.SAMPLEREF createAnalysisTypePARENTSAMPLEREF() {
        return new AnalysisType.PARENT.SAMPLEREF();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.StudySet}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudySet} object.
     */
    public StudySet createSTUDYSET() {
        return new StudySet();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PROCESSING.QUALITYSCORES}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PROCESSING.QUALITYSCORES} object.
     */
    public ExperimentType.PROCESSING.QUALITYSCORES createExperimentTypePROCESSINGQUALITYSCORES() {
        return new ExperimentType.PROCESSING.QUALITYSCORES();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLELINKS.SAMPLELINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLELINKS.SAMPLELINK} object.
     */
    public SampleType.SAMPLELINKS.SAMPLELINK createSampleTypeSAMPLELINKSSAMPLELINK() {
        return new SampleType.SAMPLELINKS.SAMPLELINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNLINKS.RUNLINK.URLLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNLINKS.RUNLINK.URLLINK} object.
     */
    public RunType.RUNLINKS.RUNLINK.URLLINK createRunTypeRUNLINKSRUNLINKURLLINK() {
        return new RunType.RUNLINKS.RUNLINK.URLLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISATTRIBUTES.ANALYSISATTRIBUTE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISATTRIBUTES.ANALYSISATTRIBUTE} object.
     */
    public AnalysisType.ANALYSISATTRIBUTES.ANALYSISATTRIBUTE createAnalysisTypeANALYSISATTRIBUTESANALYSISATTRIBUTE() {
        return new AnalysisType.ANALYSISATTRIBUTES.ANALYSISATTRIBUTE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT} object.
     */
    public AnalysisType.PARENT createAnalysisTypePARENT() {
        return new AnalysisType.PARENT();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.MEMBERS.MEMBER}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.MEMBERS.MEMBER} object.
     */
    public SampleType.MEMBERS.MEMBER createSampleTypeMEMBERSMEMBER() {
        return new SampleType.MEMBERS.MEMBER();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLEATTRIBUTES.SAMPLEATTRIBUTE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLEATTRIBUTES.SAMPLEATTRIBUTE} object.
     */
    public SampleType.SAMPLEATTRIBUTES.SAMPLEATTRIBUTE createSampleTypeSAMPLEATTRIBUTESSAMPLEATTRIBUTE() {
        return new SampleType.SAMPLEATTRIBUTES.SAMPLEATTRIBUTE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISTYPE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISTYPE} object.
     */
    public AnalysisType.ANALYSISTYPE createAnalysisTypeANALYSISTYPE() {
        return new AnalysisType.ANALYSISTYPE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLELINKS.SAMPLELINK.ENTREZLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLELINKS.SAMPLELINK.ENTREZLINK} object.
     */
    public SampleType.SAMPLELINKS.SAMPLELINK.ENTREZLINK createSampleTypeSAMPLELINKSSAMPLELINKENTREZLINK() {
        return new SampleType.SAMPLELINKS.SAMPLELINK.ENTREZLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLENAME}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLENAME} object.
     */
    public SampleType.SAMPLENAME createSampleTypeSAMPLENAME() {
        return new SampleType.SAMPLENAME();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunSet}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunSet} object.
     */
    public RunSet createRUNSET() {
        return new RunSet();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISFILES}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISFILES} object.
     */
    public AnalysisType.ANALYSISFILES createAnalysisTypeANALYSISFILES() {
        return new AnalysisType.ANALYSISFILES();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.URLLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.URLLINK} object.
     */
    public ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.URLLINK createExperimentTypeEXPERIMENTLINKSEXPERIMENTLINKURLLINK() {
        return new ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.URLLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK} object.
     */
    public StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK createStudyTypeSTUDYLINKSSTUDYLINKENTREZLINK() {
        return new StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.LIBRARYDESCRIPTOR}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.LIBRARYDESCRIPTOR} object.
     */
    public ExperimentType.DESIGN.LIBRARYDESCRIPTOR createExperimentTypeDESIGNLIBRARYDESCRIPTOR() {
        return new ExperimentType.DESIGN.LIBRARYDESCRIPTOR();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISLINKS.ANALYSISLINK.XREFLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISLINKS.ANALYSISLINK.XREFLINK} object.
     */
    public AnalysisType.ANALYSISLINKS.ANALYSISLINK.XREFLINK createAnalysisTypeANALYSISLINKSANALYSISLINKXREFLINK() {
        return new AnalysisType.ANALYSISLINKS.ANALYSISLINK.XREFLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.ENTREZLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.ENTREZLINK} object.
     */
    public ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.ENTREZLINK createExperimentTypeEXPERIMENTLINKSEXPERIMENTLINKENTREZLINK() {
        return new ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK.ENTREZLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISLINKS.ANALYSISLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISLINKS.ANALYSISLINK} object.
     */
    public AnalysisType.ANALYSISLINKS.ANALYSISLINK createAnalysisTypeANALYSISLINKSANALYSISLINK() {
        return new AnalysisType.ANALYSISLINKS.ANALYSISLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType} object.
     */
    public SubmissionType createSubmissionType() {
        return new SubmissionType();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS} object.
     */
    public SubmissionType.ACTIONS createSubmissionTypeACTIONS() {
        return new SubmissionType.ACTIONS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.LS454}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.LS454} object.
     */
    public ExperimentType.PLATFORM.LS454 createExperimentTypePLATFORMLS454() {
        return new ExperimentType.PLATFORM.LS454();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.ABISOLID.COLORMATRIX.COLOR}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.ABISOLID.COLORMATRIX.COLOR} object.
     */
    public ExperimentType.PLATFORM.ABISOLID.COLORMATRIX.COLOR createExperimentTypePLATFORMABISOLIDCOLORMATRIXCOLOR() {
        return new ExperimentType.PLATFORM.ABISOLID.COLORMATRIX.COLOR();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM} object.
     */
    public ExperimentType.PLATFORM createExperimentTypePLATFORM() {
        return new ExperimentType.PLATFORM();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.SAMPLEDESCRIPTOR}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.SAMPLEDESCRIPTOR} object.
     */
    public ExperimentType.DESIGN.SAMPLEDESCRIPTOR createExperimentTypeDESIGNSAMPLEDESCRIPTOR() {
        return new ExperimentType.DESIGN.SAMPLEDESCRIPTOR();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.DESCRIPTOR}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.DESCRIPTOR} object.
     */
    public StudyType.DESCRIPTOR createStudyTypeDESCRIPTOR() {
        return new StudyType.DESCRIPTOR();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.SAMPLEPOOLREF.MEMBER}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.PARENT.SAMPLEPOOLREF.MEMBER} object.
     */
    public AnalysisType.PARENT.SAMPLEPOOLREF.MEMBER createAnalysisTypePARENTSAMPLEPOOLREFMEMBER() {
        return new AnalysisType.PARENT.SAMPLEPOOLREF.MEMBER();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYLINKS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYLINKS} object.
     */
    public StudyType.STUDYLINKS createStudyTypeSTUDYLINKS() {
        return new StudyType.STUDYLINKS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION} object.
     */
    public SubmissionType.ACTIONS.ACTION createSubmissionTypeACTIONSACTION() {
        return new SubmissionType.ACTIONS.ACTION();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTATTRIBUTES}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTATTRIBUTES} object.
     */
    public ExperimentType.EXPERIMENTATTRIBUTES createExperimentTypeEXPERIMENTATTRIBUTES() {
        return new ExperimentType.EXPERIMENTATTRIBUTES();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.CONTACTS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.CONTACTS} object.
     */
    public SubmissionType.CONTACTS createSubmissionTypeCONTACTS() {
        return new SubmissionType.CONTACTS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.SUPPRESS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.SUPPRESS} object.
     */
    public SubmissionType.ACTIONS.ACTION.SUPPRESS createSubmissionTypeACTIONSACTIONSUPPRESS() {
        return new SubmissionType.ACTIONS.ACTION.SUPPRESS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT.PAIRED}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT.PAIRED} object.
     */
    public ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT.PAIRED createExperimentTypeDESIGNLIBRARYDESCRIPTORLIBRARYLAYOUTPAIRED() {
        return new ExperimentType.DESIGN.LIBRARYDESCRIPTOR.LIBRARYLAYOUT.PAIRED();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.FILES}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.FILES} object.
     */
    public SubmissionType.FILES createSubmissionTypeFILES() {
        return new SubmissionType.FILES();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.ABISOLID}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.ABISOLID} object.
     */
    public ExperimentType.PLATFORM.ABISOLID createExperimentTypePLATFORMABISOLID() {
        return new ExperimentType.PLATFORM.ABISOLID();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisSet}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisSet} object.
     */
    public AnalysisSet createANALYSISSET() {
        return new AnalysisSet();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType} object.
     */
    public SampleType createSampleType() {
        return new SampleType();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISATTRIBUTES}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISATTRIBUTES} object.
     */
    public AnalysisType.ANALYSISATTRIBUTES createAnalysisTypeANALYSISATTRIBUTES() {
        return new AnalysisType.ANALYSISATTRIBUTES();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNATTRIBUTES}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNATTRIBUTES} object.
     */
    public RunType.RUNATTRIBUTES createRunTypeRUNATTRIBUTES() {
        return new RunType.RUNATTRIBUTES();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK} object.
     */
    public ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK createExperimentTypeEXPERIMENTLINKSEXPERIMENTLINK() {
        return new ExperimentType.EXPERIMENTLINKS.EXPERIMENTLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.SPOTDESCRIPTOR}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.DESIGN.SPOTDESCRIPTOR} object.
     */
    public ExperimentType.DESIGN.SPOTDESCRIPTOR createExperimentTypeDESIGNSPOTDESCRIPTOR() {
        return new ExperimentType.DESIGN.SPOTDESCRIPTOR();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.ADD}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.ADD} object.
     */
    public SubmissionType.ACTIONS.ACTION.ADD createSubmissionTypeACTIONSACTIONADD() {
        return new SubmissionType.ACTIONS.ACTION.ADD();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISLINKS.ANALYSISLINK.ENTREZLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISLINKS.ANALYSISLINK.ENTREZLINK} object.
     */
    public AnalysisType.ANALYSISLINKS.ANALYSISLINK.ENTREZLINK createAnalysisTypeANALYSISLINKSANALYSISLINKENTREZLINK() {
        return new AnalysisType.ANALYSISLINKS.ANALYSISLINK.ENTREZLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLELINKS.SAMPLELINK.URLLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType.SAMPLELINKS.SAMPLELINK.URLLINK} object.
     */
    public SampleType.SAMPLELINKS.SAMPLELINK.URLLINK createSampleTypeSAMPLELINKSSAMPLELINKURLLINK() {
        return new SampleType.SAMPLELINKS.SAMPLELINK.URLLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.FILES.FILE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.FILES.FILE} object.
     */
    public SubmissionType.FILES.FILE createSubmissionTypeFILESFILE() {
        return new SubmissionType.FILES.FILE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTATTRIBUTES.EXPERIMENTATTRIBUTE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.EXPERIMENTATTRIBUTES.EXPERIMENTATTRIBUTE} object.
     */
    public ExperimentType.EXPERIMENTATTRIBUTES.EXPERIMENTATTRIBUTE createExperimentTypeEXPERIMENTATTRIBUTESEXPERIMENTATTRIBUTE() {
        return new ExperimentType.EXPERIMENTATTRIBUTES.EXPERIMENTATTRIBUTE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.DATABLOCK.FILES.FILE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.DATABLOCK.FILES.FILE} object.
     */
    public RunType.DATABLOCK.FILES.FILE createRunTypeDATABLOCKFILESFILE() {
        return new RunType.DATABLOCK.FILES.FILE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNLINKS.RUNLINK.ENTREZLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNLINKS.RUNLINK.ENTREZLINK} object.
     */
    public RunType.RUNLINKS.RUNLINK.ENTREZLINK createRunTypeRUNLINKSRUNLINKENTREZLINK() {
        return new RunType.RUNLINKS.RUNLINK.ENTREZLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNATTRIBUTES.RUNATTRIBUTE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNATTRIBUTES.RUNATTRIBUTE} object.
     */
    public RunType.RUNATTRIBUTES.RUNATTRIBUTE createRunTypeRUNATTRIBUTESRUNATTRIBUTE() {
        return new RunType.RUNATTRIBUTES.RUNATTRIBUTE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.ABISOLID.COLORMATRIX}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.ABISOLID.COLORMATRIX} object.
     */
    public ExperimentType.PLATFORM.ABISOLID.COLORMATRIX createExperimentTypePLATFORMABISOLIDCOLORMATRIX() {
        return new ExperimentType.PLATFORM.ABISOLID.COLORMATRIX();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNLINKS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNLINKS} object.
     */
    public RunType.RUNLINKS createRunTypeRUNLINKS() {
        return new RunType.RUNLINKS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType} object.
     */
    public ExperimentType createExperimentType() {
        return new ExperimentType();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYLINKS.STUDYLINK.URLLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYLINKS.STUDYLINK.URLLINK} object.
     */
    public StudyType.STUDYLINKS.STUDYLINK.URLLINK createStudyTypeSTUDYLINKSSTUDYLINKURLLINK() {
        return new StudyType.STUDYLINKS.STUDYLINK.URLLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYLINKS.STUDYLINK}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYLINKS.STUDYLINK} object.
     */
    public StudyType.STUDYLINKS.STUDYLINK createStudyTypeSTUDYLINKSSTUDYLINK() {
        return new StudyType.STUDYLINKS.STUDYLINK();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.HELICOS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PLATFORM.HELICOS} object.
     */
    public ExperimentType.PLATFORM.HELICOS createExperimentTypePLATFORMHELICOS() {
        return new ExperimentType.PLATFORM.HELICOS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.DESCRIPTOR.STUDYTYPE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.DESCRIPTOR.STUDYTYPE} object.
     */
    public StudyType.DESCRIPTOR.STUDYTYPE createStudyTypeDESCRIPTORSTUDYTYPE() {
        return new StudyType.DESCRIPTOR.STUDYTYPE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.HOLD}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.HOLD} object.
     */
    public SubmissionType.ACTIONS.ACTION.HOLD createSubmissionTypeACTIONSACTIONHOLD() {
        return new SubmissionType.ACTIONS.ACTION.HOLD();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PROCESSING}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType.PROCESSING} object.
     */
    public ExperimentType.PROCESSING createExperimentTypePROCESSING() {
        return new ExperimentType.PROCESSING();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.RunType}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType} object.
     */
    public RunType createRunType() {
        return new RunType();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISLINKS}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType.ANALYSISLINKS} object.
     */
    public AnalysisType.ANALYSISLINKS createAnalysisTypeANALYSISLINKS() {
        return new AnalysisType.ANALYSISLINKS();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE} object.
     */
    public StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE createStudyTypeSTUDYATTRIBUTESSTUDYATTRIBUTE() {
        return new StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE();
    }

    /**
     * Create an instance of {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.RELEASE}
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType.ACTIONS.ACTION.RELEASE} object.
     */
    public SubmissionType.ACTIONS.ACTION.RELEASE createSubmissionTypeACTIONSACTIONRELEASE() {
        return new SubmissionType.ACTIONS.ACTION.RELEASE();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement}{@code <}{@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType}{@code >}}
     *
     * @param value a {@link net.sourceforge.seqware.queryengine.webservice.model.ExperimentType} object.
     * @return a {@link javax.xml.bind.JAXBElement} object.
     */
    @XmlElementDecl(namespace = "", name = "EXPERIMENT")
    public JAXBElement<ExperimentType> createEXPERIMENT(ExperimentType value) {
        return new JAXBElement<ExperimentType>(_EXPERIMENT_QNAME, ExperimentType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement}{@code <}{@link net.sourceforge.seqware.queryengine.webservice.model.SampleType}{@code >}}
     *
     * @param value a {@link net.sourceforge.seqware.queryengine.webservice.model.SampleType} object.
     * @return a {@link javax.xml.bind.JAXBElement} object.
     */
    @XmlElementDecl(namespace = "", name = "SAMPLE")
    public JAXBElement<SampleType> createSAMPLE(SampleType value) {
        return new JAXBElement<SampleType>(_SAMPLE_QNAME, SampleType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement}{@code <}{@link net.sourceforge.seqware.queryengine.webservice.model.RunType}{@code >}}
     *
     * @param value a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType} object.
     * @return a {@link javax.xml.bind.JAXBElement} object.
     */
    @XmlElementDecl(namespace = "", name = "RUN")
    public JAXBElement<RunType> createRUN(RunType value) {
        return new JAXBElement<RunType>(_RUN_QNAME, RunType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement}{@code <}{@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType}{@code >}}
     *
     * @param value a {@link net.sourceforge.seqware.queryengine.webservice.model.AnalysisType} object.
     * @return a {@link javax.xml.bind.JAXBElement} object.
     */
    @XmlElementDecl(namespace = "", name = "ANALYSIS")
    public JAXBElement<AnalysisType> createANALYSIS(AnalysisType value) {
        return new JAXBElement<AnalysisType>(_ANALYSIS_QNAME, AnalysisType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement}{@code <}{@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType}{@code >}}
     *
     * @param value a {@link net.sourceforge.seqware.queryengine.webservice.model.SubmissionType} object.
     * @return a {@link javax.xml.bind.JAXBElement} object.
     */
    @XmlElementDecl(namespace = "", name = "SUBMISSION")
    public JAXBElement<SubmissionType> createSUBMISSION(SubmissionType value) {
        return new JAXBElement<SubmissionType>(_SUBMISSION_QNAME, SubmissionType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement}{@code <}{@link net.sourceforge.seqware.queryengine.webservice.model.StudyType}{@code >}}
     *
     * @param value a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType} object.
     * @return a {@link javax.xml.bind.JAXBElement} object.
     */
    @XmlElementDecl(namespace = "", name = "STUDY")
    public JAXBElement<StudyType> createSTUDY(StudyType value) {
        return new JAXBElement<StudyType>(_STUDY_QNAME, StudyType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement}{@code <}{@link java.lang.String}{@code >}}
     *
     * @param value a {@link java.lang.String} object.
     * @return a {@link javax.xml.bind.JAXBElement} object.
     */
    @XmlElementDecl(namespace = "", name = "STUDY_ABSTRACT", scope = StudyType.DESCRIPTOR.class)
    public JAXBElement<String> createStudyTypeDESCRIPTORSTUDYABSTRACT(String value) {
        return new JAXBElement<String>(_StudyTypeDESCRIPTORSTUDYABSTRACT_QNAME, String.class, StudyType.DESCRIPTOR.class, value);
    }

}
