//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.14 at 03:13:03 PM PDT 
//


package net.sourceforge.seqware.queryengine.webservice.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 *
 *                 A Run contains the sequencing results from a particular run on a sequencing instrument.  The Run was done in fulfillment
 *                 of an Experiment that was designed into the Study.
 *                 One SRA run may consist of only a portion of the plate or slide if the instrument run was partitioned among distinct experiments
 *                 or between distinct RUNs.  By policy the Center should separate these data into distinct SRA Run objects.
 *
 *
 * <p>Java class for RunType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RunType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EXPERIMENT_REF">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="accession" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="refname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;element name="DATA_BLOCK">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="FILES">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence maxOccurs="unbounded">
 *                               &lt;element name="FILE">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                       &lt;attribute name="filetype">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;enumeration value="srf"/>
 *                                             &lt;enumeration value="sff"/>
 *                                             &lt;enumeration value="fastq"/>
 *                                             &lt;enumeration value="_seq.txt, _prb.txt, _sig2.txt, _qhg.txt"/>
 *                                             &lt;enumeration value="Illumina_native"/>
 *                                             &lt;enumeration value="SOLiD_native"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/attribute>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="sector" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                   &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                   &lt;attribute name="total_spots" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                   &lt;attribute name="total_reads" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                   &lt;attribute name="number_channels" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                   &lt;attribute name="format_code" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="RUN_LINKS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="RUN_LINK">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="URL_LINK">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                     &lt;/all>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ENTREZ_LINK">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/all>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RUN_ATTRIBUTES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="RUN_ATTRIBUTE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="TAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UNITS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="accession" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="instrument_model">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="454 GS"/>
 *             &lt;enumeration value="454 GS 20"/>
 *             &lt;enumeration value="454 GS FLX"/>
 *             &lt;enumeration value="Solexa 1G Genome Analyzer"/>
 *             &lt;enumeration value="Illumina Genome Analyzer"/>
 *             &lt;enumeration value="Illumina Genome Analyzer II"/>
 *             &lt;enumeration value="AB SOLiD System"/>
 *             &lt;enumeration value="AB SOLiD System 2.0"/>
 *             &lt;enumeration value="Other"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="instrument_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="run_date" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="run_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="run_center" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="total_data_blocks" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 * @author morgantaschuk
 * @version $Id: $Id
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RunType", propOrder = {
    "experimentref",
    "datablock",
    "runlinks",
    "runattributes"
})
public class RunType {

    @XmlElement(name = "EXPERIMENT_REF", required = true)
    protected RunType.EXPERIMENTREF experimentref;
    @XmlElement(name = "DATA_BLOCK", required = true)
    protected List<RunType.DATABLOCK> datablock;
    @XmlElement(name = "RUN_LINKS")
    protected RunType.RUNLINKS runlinks;
    @XmlElement(name = "RUN_ATTRIBUTES")
    protected RunType.RUNATTRIBUTES runattributes;
    @XmlAttribute
    protected String alias;
    @XmlAttribute
    protected String accession;
    @XmlAttribute(name = "instrument_model")
    protected String instrumentModel;
    @XmlAttribute(name = "instrument_name")
    protected String instrumentName;
    @XmlAttribute(name = "run_date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar runDate;
    @XmlAttribute(name = "run_file")
    protected String runFile;
    @XmlAttribute(name = "run_center")
    protected String runCenter;
    @XmlAttribute(name = "total_data_blocks", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger totalDataBlocks;

    /**
     * Gets the value of the experimentref property.
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.EXPERIMENTREF} object.
     */
    public RunType.EXPERIMENTREF getEXPERIMENTREF() {
        return experimentref;
    }

    /**
     * Sets the value of the experimentref property.
     *
     * @param value
     *     allowed object is
     *     {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.EXPERIMENTREF}
     */
    public void setEXPERIMENTREF(RunType.EXPERIMENTREF value) {
        this.experimentref = value;
    }

    /**
     * Gets the value of the datablock property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datablock property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDATABLOCK().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.DATABLOCK}
     *
     * @return a {@link java.util.List} object.
     */
    public List<RunType.DATABLOCK> getDATABLOCK() {
        if (datablock == null) {
            datablock = new ArrayList<RunType.DATABLOCK>();
        }
        return this.datablock;
    }

    /**
     * Gets the value of the runlinks property.
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNLINKS} object.
     */
    public RunType.RUNLINKS getRUNLINKS() {
        return runlinks;
    }

    /**
     * Sets the value of the runlinks property.
     *
     * @param value
     *     allowed object is
     *     {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNLINKS}
     */
    public void setRUNLINKS(RunType.RUNLINKS value) {
        this.runlinks = value;
    }

    /**
     * Gets the value of the runattributes property.
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNATTRIBUTES} object.
     */
    public RunType.RUNATTRIBUTES getRUNATTRIBUTES() {
        return runattributes;
    }

    /**
     * Sets the value of the runattributes property.
     *
     * @param value
     *     allowed object is
     *     {@link net.sourceforge.seqware.queryengine.webservice.model.RunType.RUNATTRIBUTES}
     */
    public void setRUNATTRIBUTES(RunType.RUNATTRIBUTES value) {
        this.runattributes = value;
    }

    /**
     * Gets the value of the alias property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the accession property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getAccession() {
        return accession;
    }

    /**
     * Sets the value of the accession property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setAccession(String value) {
        this.accession = value;
    }

    /**
     * Gets the value of the instrumentModel property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getInstrumentModel() {
        return instrumentModel;
    }

    /**
     * Sets the value of the instrumentModel property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setInstrumentModel(String value) {
        this.instrumentModel = value;
    }

    /**
     * Gets the value of the instrumentName property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getInstrumentName() {
        return instrumentName;
    }

    /**
     * Sets the value of the instrumentName property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setInstrumentName(String value) {
        this.instrumentName = value;
    }

    /**
     * Gets the value of the runDate property.
     *
     * @return a {@link javax.xml.datatype.XMLGregorianCalendar} object.
     */
    public XMLGregorianCalendar getRunDate() {
        return runDate;
    }

    /**
     * Sets the value of the runDate property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar}
     */
    public void setRunDate(XMLGregorianCalendar value) {
        this.runDate = value;
    }

    /**
     * Gets the value of the runFile property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getRunFile() {
        return runFile;
    }

    /**
     * Sets the value of the runFile property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setRunFile(String value) {
        this.runFile = value;
    }

    /**
     * Gets the value of the runCenter property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getRunCenter() {
        return runCenter;
    }

    /**
     * Sets the value of the runCenter property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setRunCenter(String value) {
        this.runCenter = value;
    }

    /**
     * Gets the value of the totalDataBlocks property.
     *
     * @return a {@link java.math.BigInteger} object.
     */
    public BigInteger getTotalDataBlocks() {
        return totalDataBlocks;
    }

    /**
     * Sets the value of the totalDataBlocks property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger}
     */
    public void setTotalDataBlocks(BigInteger value) {
        this.totalDataBlocks = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FILES">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="FILE">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="filetype">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="srf"/>
     *                                 &lt;enumeration value="sff"/>
     *                                 &lt;enumeration value="fastq"/>
     *                                 &lt;enumeration value="_seq.txt, _prb.txt, _sig2.txt, _qhg.txt"/>
     *                                 &lt;enumeration value="Illumina_native"/>
     *                                 &lt;enumeration value="SOLiD_native"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="sector" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="total_spots" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="total_reads" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="number_channels" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="format_code" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "files"
    })
    public static class DATABLOCK {

        @XmlElement(name = "FILES", required = true)
        protected RunType.DATABLOCK.FILES files;
        @XmlAttribute
        protected String name;
        @XmlAttribute
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger sector;
        @XmlAttribute
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger region;
        @XmlAttribute(name = "total_spots")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger totalSpots;
        @XmlAttribute(name = "total_reads")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger totalReads;
        @XmlAttribute(name = "number_channels")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger numberChannels;
        @XmlAttribute(name = "format_code")
        protected Integer formatCode;

        /**
         * Gets the value of the files property.
         * 
         * @return
         *     possible object is
         *     {@link RunType.DATABLOCK.FILES }
         *     
         */
        public RunType.DATABLOCK.FILES getFILES() {
            return files;
        }

        /**
         * Sets the value of the files property.
         * 
         * @param value
         *     allowed object is
         *     {@link RunType.DATABLOCK.FILES }
         *     
         */
        public void setFILES(RunType.DATABLOCK.FILES value) {
            this.files = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the sector property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSector() {
            return sector;
        }

        /**
         * Sets the value of the sector property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSector(BigInteger value) {
            this.sector = value;
        }

        /**
         * Gets the value of the region property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRegion() {
            return region;
        }

        /**
         * Sets the value of the region property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRegion(BigInteger value) {
            this.region = value;
        }

        /**
         * Gets the value of the totalSpots property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalSpots() {
            return totalSpots;
        }

        /**
         * Sets the value of the totalSpots property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalSpots(BigInteger value) {
            this.totalSpots = value;
        }

        /**
         * Gets the value of the totalReads property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalReads() {
            return totalReads;
        }

        /**
         * Sets the value of the totalReads property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalReads(BigInteger value) {
            this.totalReads = value;
        }

        /**
         * Gets the value of the numberChannels property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberChannels() {
            return numberChannels;
        }

        /**
         * Sets the value of the numberChannels property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberChannels(BigInteger value) {
            this.numberChannels = value;
        }

        /**
         * Gets the value of the formatCode property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getFormatCode() {
            return formatCode;
        }

        /**
         * Sets the value of the formatCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setFormatCode(Integer value) {
            this.formatCode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="FILE">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="filetype">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="srf"/>
         *                       &lt;enumeration value="sff"/>
         *                       &lt;enumeration value="fastq"/>
         *                       &lt;enumeration value="_seq.txt, _prb.txt, _sig2.txt, _qhg.txt"/>
         *                       &lt;enumeration value="Illumina_native"/>
         *                       &lt;enumeration value="SOLiD_native"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "file"
        })
        public static class FILES {

            @XmlElement(name = "FILE", required = true)
            protected List<RunType.DATABLOCK.FILES.FILE> file;

            /**
             * Gets the value of the file property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the file property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFILE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RunType.DATABLOCK.FILES.FILE }
             * 
             * 
             */
            public List<RunType.DATABLOCK.FILES.FILE> getFILE() {
                if (file == null) {
                    file = new ArrayList<RunType.DATABLOCK.FILES.FILE>();
                }
                return this.file;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="filetype">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="srf"/>
             *             &lt;enumeration value="sff"/>
             *             &lt;enumeration value="fastq"/>
             *             &lt;enumeration value="_seq.txt, _prb.txt, _sig2.txt, _qhg.txt"/>
             *             &lt;enumeration value="Illumina_native"/>
             *             &lt;enumeration value="SOLiD_native"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class FILE {

                @XmlAttribute
                protected String filename;
                @XmlAttribute
                protected String filetype;

                /**
                 * Gets the value of the filename property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFilename() {
                    return filename;
                }

                /**
                 * Sets the value of the filename property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFilename(String value) {
                    this.filename = value;
                }

                /**
                 * Gets the value of the filetype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFiletype() {
                    return filetype;
                }

                /**
                 * Sets the value of the filetype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFiletype(String value) {
                    this.filetype = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="accession" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="refname" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EXPERIMENTREF {

        @XmlAttribute
        protected String accession;
        @XmlAttribute
        protected String refname;

        /**
         * Gets the value of the accession property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccession() {
            return accession;
        }

        /**
         * Sets the value of the accession property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccession(String value) {
            this.accession = value;
        }

        /**
         * Gets the value of the refname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefname() {
            return refname;
        }

        /**
         * Sets the value of the refname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefname(String value) {
            this.refname = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="RUN_ATTRIBUTE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="TAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UNITS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "runattribute"
    })
    public static class RUNATTRIBUTES {

        @XmlElement(name = "RUN_ATTRIBUTE", required = true)
        protected List<RunType.RUNATTRIBUTES.RUNATTRIBUTE> runattribute;

        /**
         * Gets the value of the runattribute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the runattribute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRUNATTRIBUTE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RunType.RUNATTRIBUTES.RUNATTRIBUTE }
         * 
         * 
         */
        public List<RunType.RUNATTRIBUTES.RUNATTRIBUTE> getRUNATTRIBUTE() {
            if (runattribute == null) {
                runattribute = new ArrayList<RunType.RUNATTRIBUTES.RUNATTRIBUTE>();
            }
            return this.runattribute;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="TAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UNITS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class RUNATTRIBUTE {

            @XmlElement(name = "TAG", required = true)
            protected String tag;
            @XmlElement(name = "VALUE", required = true)
            protected String value;
            @XmlElement(name = "UNITS")
            protected String units;

            /**
             * Gets the value of the tag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTAG() {
                return tag;
            }

            /**
             * Sets the value of the tag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTAG(String value) {
                this.tag = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVALUE() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVALUE(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUNITS() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUNITS(String value) {
                this.units = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="RUN_LINK">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="URL_LINK">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                           &lt;/all>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ENTREZ_LINK">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/all>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "runlink"
    })
    public static class RUNLINKS {

        @XmlElement(name = "RUN_LINK", required = true)
        protected List<RunType.RUNLINKS.RUNLINK> runlink;

        /**
         * Gets the value of the runlink property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the runlink property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRUNLINK().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RunType.RUNLINKS.RUNLINK }
         * 
         * 
         */
        public List<RunType.RUNLINKS.RUNLINK> getRUNLINK() {
            if (runlink == null) {
                runlink = new ArrayList<RunType.RUNLINKS.RUNLINK>();
            }
            return this.runlink;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="URL_LINK">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                 &lt;/all>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ENTREZ_LINK">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/all>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "urllink",
            "entrezlink"
        })
        public static class RUNLINK {

            @XmlElement(name = "URL_LINK")
            protected RunType.RUNLINKS.RUNLINK.URLLINK urllink;
            @XmlElement(name = "ENTREZ_LINK")
            protected RunType.RUNLINKS.RUNLINK.ENTREZLINK entrezlink;

            /**
             * Gets the value of the urllink property.
             * 
             * @return
             *     possible object is
             *     {@link RunType.RUNLINKS.RUNLINK.URLLINK }
             *     
             */
            public RunType.RUNLINKS.RUNLINK.URLLINK getURLLINK() {
                return urllink;
            }

            /**
             * Sets the value of the urllink property.
             * 
             * @param value
             *     allowed object is
             *     {@link RunType.RUNLINKS.RUNLINK.URLLINK }
             *     
             */
            public void setURLLINK(RunType.RUNLINKS.RUNLINK.URLLINK value) {
                this.urllink = value;
            }

            /**
             * Gets the value of the entrezlink property.
             * 
             * @return
             *     possible object is
             *     {@link RunType.RUNLINKS.RUNLINK.ENTREZLINK }
             *     
             */
            public RunType.RUNLINKS.RUNLINK.ENTREZLINK getENTREZLINK() {
                return entrezlink;
            }

            /**
             * Sets the value of the entrezlink property.
             * 
             * @param value
             *     allowed object is
             *     {@link RunType.RUNLINKS.RUNLINK.ENTREZLINK }
             *     
             */
            public void setENTREZLINK(RunType.RUNLINKS.RUNLINK.ENTREZLINK value) {
                this.entrezlink = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/all>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class ENTREZLINK {

                @XmlElement(name = "DB", required = true)
                protected String db;
                @XmlElement(name = "ID", required = true)
                protected String id;

                /**
                 * Gets the value of the db property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDB() {
                    return db;
                }

                /**
                 * Sets the value of the db property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDB(String value) {
                    this.db = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getID() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setID(String value) {
                    this.id = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *       &lt;/all>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class URLLINK {

                @XmlElement(name = "LABEL", required = true)
                protected String label;
                @XmlElement(name = "URL", required = true)
                @XmlSchemaType(name = "anyURI")
                protected String url;

                /**
                 * Gets the value of the label property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLABEL() {
                    return label;
                }

                /**
                 * Sets the value of the label property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLABEL(String value) {
                    this.label = value;
                }

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getURL() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setURL(String value) {
                    this.url = value;
                }

            }

        }

    }

}
