//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.14 at 03:13:03 PM PDT 
//


package net.sourceforge.seqware.queryengine.webservice.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 *
 *           A Study is a container for a sequencing investigation that may comprise multiple experiments.
 *           The Study has an overall goal, but is otherwise minimally defined in the SRA.
 *           A Study is composed of a descriptor, zero or more experiments, and zero or more analyses.
 *           The submitter may decorate the Study with web links and properties.
 *
 *
 * <p>Java class for StudyType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StudyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DESCRIPTOR">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="STUDY_TITLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="STUDY_TYPE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="existing_study_type" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="Whole Genome Sequencing"/>
 *                                 &lt;enumeration value="Metagenomics"/>
 *                                 &lt;enumeration value="Transcriptome Analysis"/>
 *                                 &lt;enumeration value="Resequencing"/>
 *                                 &lt;enumeration value="Epigenetics"/>
 *                                 &lt;enumeration value="Synthetic Genomics"/>
 *                                 &lt;enumeration value="Forensic or Paleo-genomics"/>
 *                                 &lt;enumeration value="Gene Regulation Study"/>
 *                                 &lt;enumeration value="Cancer Genomics"/>
 *                                 &lt;enumeration value="Population Genomics"/>
 *                                 &lt;enumeration value="Other"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="new_study_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="STUDY_ABSTRACT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CENTER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CENTER_PROJECT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PROJECT_ID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="STUDY_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="STUDY_LINKS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="STUDY_LINK">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="URL_LINK">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                     &lt;/all>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="ENTREZ_LINK">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/all>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="STUDY_ATTRIBUTES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="STUDY_ATTRIBUTE">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="TAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UNITS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="alias" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="accession" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 * @author morgantaschuk
 * @version $Id: $Id
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudyType", propOrder = {
    "descriptor",
    "studylinks",
    "studyattributes"
})
public class StudyType {

    @XmlElement(name = "DESCRIPTOR", required = true)
    protected StudyType.DESCRIPTOR descriptor;
    @XmlElement(name = "STUDY_LINKS")
    protected StudyType.STUDYLINKS studylinks;
    @XmlElement(name = "STUDY_ATTRIBUTES")
    protected StudyType.STUDYATTRIBUTES studyattributes;
    @XmlAttribute
    protected String alias;
    @XmlAttribute
    protected String accession;

    /**
     * Gets the value of the descriptor property.
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.DESCRIPTOR} object.
     */
    public StudyType.DESCRIPTOR getDESCRIPTOR() {
        return descriptor;
    }

    /**
     * Sets the value of the descriptor property.
     *
     * @param value
     *     allowed object is
     *     {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.DESCRIPTOR}
     */
    public void setDESCRIPTOR(StudyType.DESCRIPTOR value) {
        this.descriptor = value;
    }

    /**
     * Gets the value of the studylinks property.
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYLINKS} object.
     */
    public StudyType.STUDYLINKS getSTUDYLINKS() {
        return studylinks;
    }

    /**
     * Sets the value of the studylinks property.
     *
     * @param value
     *     allowed object is
     *     {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYLINKS}
     */
    public void setSTUDYLINKS(StudyType.STUDYLINKS value) {
        this.studylinks = value;
    }

    /**
     * Gets the value of the studyattributes property.
     *
     * @return a {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYATTRIBUTES} object.
     */
    public StudyType.STUDYATTRIBUTES getSTUDYATTRIBUTES() {
        return studyattributes;
    }

    /**
     * Sets the value of the studyattributes property.
     *
     * @param value
     *     allowed object is
     *     {@link net.sourceforge.seqware.queryengine.webservice.model.StudyType.STUDYATTRIBUTES}
     */
    public void setSTUDYATTRIBUTES(StudyType.STUDYATTRIBUTES value) {
        this.studyattributes = value;
    }

    /**
     * Gets the value of the alias property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the accession property.
     *
     * @return a {@link java.lang.String} object.
     */
    public String getAccession() {
        return accession;
    }

    /**
     * Sets the value of the accession property.
     *
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    public void setAccession(String value) {
        this.accession = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="STUDY_TITLE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="STUDY_TYPE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="existing_study_type" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="Whole Genome Sequencing"/>
     *                       &lt;enumeration value="Metagenomics"/>
     *                       &lt;enumeration value="Transcriptome Analysis"/>
     *                       &lt;enumeration value="Resequencing"/>
     *                       &lt;enumeration value="Epigenetics"/>
     *                       &lt;enumeration value="Synthetic Genomics"/>
     *                       &lt;enumeration value="Forensic or Paleo-genomics"/>
     *                       &lt;enumeration value="Gene Regulation Study"/>
     *                       &lt;enumeration value="Cancer Genomics"/>
     *                       &lt;enumeration value="Population Genomics"/>
     *                       &lt;enumeration value="Other"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="new_study_type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="STUDY_ABSTRACT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CENTER_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CENTER_PROJECT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PROJECT_ID" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="STUDY_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class DESCRIPTOR {

        @XmlElement(name = "STUDY_TITLE", required = true)
        protected String studytitle;
        @XmlElement(name = "STUDY_TYPE", required = true)
        protected StudyType.DESCRIPTOR.STUDYTYPE studytype;
        @XmlElementRef(name = "STUDY_ABSTRACT", type = JAXBElement.class)
        protected JAXBElement<String> studyabstract;
        @XmlElement(name = "CENTER_NAME", required = true)
        protected String centername;
        @XmlElement(name = "CENTER_PROJECT_NAME", required = true)
        protected String centerprojectname;
        @XmlElement(name = "PROJECT_ID", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger projectid;
        @XmlElement(name = "STUDY_DESCRIPTION")
        protected String studydescription;

        /**
         * Gets the value of the studytitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTUDYTITLE() {
            return studytitle;
        }

        /**
         * Sets the value of the studytitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTUDYTITLE(String value) {
            this.studytitle = value;
        }

        /**
         * Gets the value of the studytype property.
         * 
         * @return
         *     possible object is
         *     {@link StudyType.DESCRIPTOR.STUDYTYPE }
         *     
         */
        public StudyType.DESCRIPTOR.STUDYTYPE getSTUDYTYPE() {
            return studytype;
        }

        /**
         * Sets the value of the studytype property.
         * 
         * @param value
         *     allowed object is
         *     {@link StudyType.DESCRIPTOR.STUDYTYPE }
         *     
         */
        public void setSTUDYTYPE(StudyType.DESCRIPTOR.STUDYTYPE value) {
            this.studytype = value;
        }

        /**
         * Gets the value of the studyabstract property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public JAXBElement<String> getSTUDYABSTRACT() {
            return studyabstract;
        }

        /**
         * Sets the value of the studyabstract property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     
         */
        public void setSTUDYABSTRACT(JAXBElement<String> value) {
            this.studyabstract = ((JAXBElement<String> ) value);
        }

        /**
         * Gets the value of the centername property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCENTERNAME() {
            return centername;
        }

        /**
         * Sets the value of the centername property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCENTERNAME(String value) {
            this.centername = value;
        }

        /**
         * Gets the value of the centerprojectname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCENTERPROJECTNAME() {
            return centerprojectname;
        }

        /**
         * Sets the value of the centerprojectname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCENTERPROJECTNAME(String value) {
            this.centerprojectname = value;
        }

        /**
         * Gets the value of the projectid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPROJECTID() {
            return projectid;
        }

        /**
         * Sets the value of the projectid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPROJECTID(BigInteger value) {
            this.projectid = value;
        }

        /**
         * Gets the value of the studydescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTUDYDESCRIPTION() {
            return studydescription;
        }

        /**
         * Sets the value of the studydescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTUDYDESCRIPTION(String value) {
            this.studydescription = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="existing_study_type" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="Whole Genome Sequencing"/>
         *             &lt;enumeration value="Metagenomics"/>
         *             &lt;enumeration value="Transcriptome Analysis"/>
         *             &lt;enumeration value="Resequencing"/>
         *             &lt;enumeration value="Epigenetics"/>
         *             &lt;enumeration value="Synthetic Genomics"/>
         *             &lt;enumeration value="Forensic or Paleo-genomics"/>
         *             &lt;enumeration value="Gene Regulation Study"/>
         *             &lt;enumeration value="Cancer Genomics"/>
         *             &lt;enumeration value="Population Genomics"/>
         *             &lt;enumeration value="Other"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="new_study_type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class STUDYTYPE {

            @XmlAttribute(name = "existing_study_type", required = true)
            protected String existingStudyType;
            @XmlAttribute(name = "new_study_type")
            protected String newStudyType;

            /**
             * Gets the value of the existingStudyType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExistingStudyType() {
                return existingStudyType;
            }

            /**
             * Sets the value of the existingStudyType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExistingStudyType(String value) {
                this.existingStudyType = value;
            }

            /**
             * Gets the value of the newStudyType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNewStudyType() {
                return newStudyType;
            }

            /**
             * Sets the value of the newStudyType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNewStudyType(String value) {
                this.newStudyType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="STUDY_ATTRIBUTE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="TAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UNITS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "studyattribute"
    })
    public static class STUDYATTRIBUTES {

        @XmlElement(name = "STUDY_ATTRIBUTE", required = true)
        protected List<StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE> studyattribute;

        /**
         * Gets the value of the studyattribute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the studyattribute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSTUDYATTRIBUTE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE }
         * 
         * 
         */
        public List<StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE> getSTUDYATTRIBUTE() {
            if (studyattribute == null) {
                studyattribute = new ArrayList<StudyType.STUDYATTRIBUTES.STUDYATTRIBUTE>();
            }
            return this.studyattribute;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="TAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="VALUE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UNITS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class STUDYATTRIBUTE {

            @XmlElement(name = "TAG", required = true)
            protected String tag;
            @XmlElement(name = "VALUE", required = true)
            protected String value;
            @XmlElement(name = "UNITS")
            protected String units;

            /**
             * Gets the value of the tag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTAG() {
                return tag;
            }

            /**
             * Sets the value of the tag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTAG(String value) {
                this.tag = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVALUE() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVALUE(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUNITS() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUNITS(String value) {
                this.units = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="STUDY_LINK">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="URL_LINK">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                           &lt;/all>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="ENTREZ_LINK">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;all>
     *                             &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/all>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "studylink"
    })
    public static class STUDYLINKS {

        @XmlElement(name = "STUDY_LINK", required = true)
        protected List<StudyType.STUDYLINKS.STUDYLINK> studylink;

        /**
         * Gets the value of the studylink property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the studylink property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSTUDYLINK().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StudyType.STUDYLINKS.STUDYLINK }
         * 
         * 
         */
        public List<StudyType.STUDYLINKS.STUDYLINK> getSTUDYLINK() {
            if (studylink == null) {
                studylink = new ArrayList<StudyType.STUDYLINKS.STUDYLINK>();
            }
            return this.studylink;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="URL_LINK">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                 &lt;/all>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="ENTREZ_LINK">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;all>
         *                   &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/all>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "urllink",
            "entrezlink"
        })
        public static class STUDYLINK {

            @XmlElement(name = "URL_LINK")
            protected StudyType.STUDYLINKS.STUDYLINK.URLLINK urllink;
            @XmlElement(name = "ENTREZ_LINK")
            protected StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK entrezlink;

            /**
             * Gets the value of the urllink property.
             * 
             * @return
             *     possible object is
             *     {@link StudyType.STUDYLINKS.STUDYLINK.URLLINK }
             *     
             */
            public StudyType.STUDYLINKS.STUDYLINK.URLLINK getURLLINK() {
                return urllink;
            }

            /**
             * Sets the value of the urllink property.
             * 
             * @param value
             *     allowed object is
             *     {@link StudyType.STUDYLINKS.STUDYLINK.URLLINK }
             *     
             */
            public void setURLLINK(StudyType.STUDYLINKS.STUDYLINK.URLLINK value) {
                this.urllink = value;
            }

            /**
             * Gets the value of the entrezlink property.
             * 
             * @return
             *     possible object is
             *     {@link StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK }
             *     
             */
            public StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK getENTREZLINK() {
                return entrezlink;
            }

            /**
             * Sets the value of the entrezlink property.
             * 
             * @param value
             *     allowed object is
             *     {@link StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK }
             *     
             */
            public void setENTREZLINK(StudyType.STUDYLINKS.STUDYLINK.ENTREZLINK value) {
                this.entrezlink = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="DB" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/all>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class ENTREZLINK {

                @XmlElement(name = "DB", required = true)
                protected String db;
                @XmlElement(name = "ID", required = true)
                protected String id;

                /**
                 * Gets the value of the db property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDB() {
                    return db;
                }

                /**
                 * Sets the value of the db property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDB(String value) {
                    this.db = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getID() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setID(String value) {
                    this.id = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;all>
             *         &lt;element name="LABEL" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *       &lt;/all>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class URLLINK {

                @XmlElement(name = "LABEL", required = true)
                protected String label;
                @XmlElement(name = "URL", required = true)
                @XmlSchemaType(name = "anyURI")
                protected String url;

                /**
                 * Gets the value of the label property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLABEL() {
                    return label;
                }

                /**
                 * Sets the value of the label property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLABEL(String value) {
                    this.label = value;
                }

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getURL() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setURL(String value) {
                    this.url = value;
                }

            }

        }

    }

}
