/**
 * 
 */
package net.sourceforge.seqware.queryengine.tools.importers.workers;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.zip.GZIPInputStream;

import net.sourceforge.seqware.queryengine.backend.model.Coverage;
import net.sourceforge.seqware.queryengine.backend.model.Variant;
import net.sourceforge.seqware.queryengine.backend.store.Store;
import net.sourceforge.seqware.queryengine.backend.store.impl.BerkeleyDBStore;
import net.sourceforge.seqware.queryengine.tools.importers.Importer;
import net.sourceforge.seqware.queryengine.tools.importers.VariantImporter;

/**
 * <p>ImportWorker class.</p>
 *
 * @author boconnor
 * @version $Id: $Id
 */
public class ImportWorker extends Thread {

  String workerName = null;
  Importer pmi = null;
  Store store = null;
  String input = null;
  boolean compressed = false;
  int minCoverage;
  int maxCoverage;
  float minSnpQuality;
  boolean includeSNV;
  int fastqConvNum;
  boolean includeIndels;
  boolean includeCoverage = false;
  int binSize = 0;

  /**
   * <p>Constructor for ImportWorker.</p>
   */
  public ImportWorker() { }
  
  /**
   * <p>Constructor for ImportWorker.</p>
   *
   * @param workerName a {@link java.lang.String} object.
   * @param pmi a {@link net.sourceforge.seqware.queryengine.tools.importers.Importer} object.
   * @param store a {@link net.sourceforge.seqware.queryengine.backend.store.Store} object.
   * @param input a {@link java.lang.String} object.
   * @param compressed a boolean.
   * @param minCoverage a int.
   * @param maxCoverage a int.
   * @param minSnpQuality a float.
   * @param includeSNV a boolean.
   * @param fastqConvNum a int.
   * @param includeIndels a boolean.
   * @param includeCoverage a boolean.
   * @param binSize a int.
   */
  public ImportWorker(String workerName, Importer pmi, Store store, String input, 
      boolean compressed, int minCoverage, int maxCoverage, float minSnpQuality, boolean includeSNV,
      int fastqConvNum, boolean includeIndels, boolean includeCoverage, int binSize) {
    this.workerName = workerName;
    this.pmi = pmi;
    this.store = store;
    this.input = input;
    this.compressed = compressed;
    this.minCoverage = minCoverage;
    this.maxCoverage = maxCoverage;
    this.minSnpQuality = minSnpQuality;
    this.includeSNV = includeSNV;
    this.fastqConvNum = fastqConvNum;
    this.includeIndels = includeIndels;
    this.includeCoverage = includeCoverage;
    this.binSize = binSize;
  }

  /**
   * <p>run.</p>
   */
  public void run() { }
 
  // autogenerated
  
  /**
   * <p>Getter for the field <code>workerName</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getWorkerName() {
    return workerName;
  }

  /**
   * <p>Setter for the field <code>workerName</code>.</p>
   *
   * @param workerName a {@link java.lang.String} object.
   */
  public void setWorkerName(String workerName) {
    this.workerName = workerName;
  }

  /**
   * <p>Getter for the field <code>pmi</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.queryengine.tools.importers.Importer} object.
   */
  public Importer getPmi() {
    return pmi;
  }

  /**
   * <p>Setter for the field <code>pmi</code>.</p>
   *
   * @param pmi a {@link net.sourceforge.seqware.queryengine.tools.importers.Importer} object.
   */
  public void setPmi(Importer pmi) {
    this.pmi = pmi;
  }

  /**
   * <p>Getter for the field <code>store</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.queryengine.backend.store.Store} object.
   */
  public Store getStore() {
    return store;
  }

  /**
   * <p>Setter for the field <code>store</code>.</p>
   *
   * @param store a {@link net.sourceforge.seqware.queryengine.backend.store.Store} object.
   */
  public void setStore(Store store) {
    this.store = store;
  }

  /**
   * <p>Getter for the field <code>input</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getInput() {
    return input;
  }

  /**
   * <p>Setter for the field <code>input</code>.</p>
   *
   * @param input a {@link java.lang.String} object.
   */
  public void setInput(String input) {
    this.input = input;
  }

  /**
   * <p>isCompressed.</p>
   *
   * @return a boolean.
   */
  public boolean isCompressed() {
    return compressed;
  }

  /**
   * <p>Setter for the field <code>compressed</code>.</p>
   *
   * @param compressed a boolean.
   */
  public void setCompressed(boolean compressed) {
    this.compressed = compressed;
  }

  /**
   * <p>Getter for the field <code>minCoverage</code>.</p>
   *
   * @return a int.
   */
  public int getMinCoverage() {
    return minCoverage;
  }

  /**
   * <p>Setter for the field <code>minCoverage</code>.</p>
   *
   * @param minCoverage a int.
   */
  public void setMinCoverage(int minCoverage) {
    this.minCoverage = minCoverage;
  }

  /**
   * <p>Getter for the field <code>maxCoverage</code>.</p>
   *
   * @return a int.
   */
  public int getMaxCoverage() {
    return maxCoverage;
  }

  /**
   * <p>Setter for the field <code>maxCoverage</code>.</p>
   *
   * @param maxCoverage a int.
   */
  public void setMaxCoverage(int maxCoverage) {
    this.maxCoverage = maxCoverage;
  }

  /**
   * <p>Getter for the field <code>minSnpQuality</code>.</p>
   *
   * @return a float.
   */
  public float getMinSnpQuality() {
    return minSnpQuality;
  }

  /**
   * <p>Setter for the field <code>minSnpQuality</code>.</p>
   *
   * @param minSnpQuality a float.
   */
  public void setMinSnpQuality(float minSnpQuality) {
    this.minSnpQuality = minSnpQuality;
  }

  /**
   * <p>isIncludeSNV.</p>
   *
   * @return a boolean.
   */
  public boolean isIncludeSNV() {
    return includeSNV;
  }

  /**
   * <p>Setter for the field <code>includeSNV</code>.</p>
   *
   * @param includeSNV a boolean.
   */
  public void setIncludeSNV(boolean includeSNV) {
    this.includeSNV = includeSNV;
  }

  /**
   * <p>Getter for the field <code>fastqConvNum</code>.</p>
   *
   * @return a int.
   */
  public int getFastqConvNum() {
    return fastqConvNum;
  }

  /**
   * <p>Setter for the field <code>fastqConvNum</code>.</p>
   *
   * @param fastqConvNum a int.
   */
  public void setFastqConvNum(int fastqConvNum) {
    this.fastqConvNum = fastqConvNum;
  }

  /**
   * <p>isIncludeIndels.</p>
   *
   * @return a boolean.
   */
  public boolean isIncludeIndels() {
    return includeIndels;
  }

  /**
   * <p>Setter for the field <code>includeIndels</code>.</p>
   *
   * @param includeIndels a boolean.
   */
  public void setIncludeIndels(boolean includeIndels) {
    this.includeIndels = includeIndels;
  }

  /**
   * <p>isIncludeCoverage.</p>
   *
   * @return a boolean.
   */
  public boolean isIncludeCoverage() {
    return includeCoverage;
  }

  /**
   * <p>Setter for the field <code>includeCoverage</code>.</p>
   *
   * @param includeCoverage a boolean.
   */
  public void setIncludeCoverage(boolean includeCoverage) {
    this.includeCoverage = includeCoverage;
  }

  /**
   * <p>Getter for the field <code>binSize</code>.</p>
   *
   * @return a int.
   */
  public int getBinSize() {
    return binSize;
  }

  /**
   * <p>Setter for the field <code>binSize</code>.</p>
   *
   * @param binSize a int.
   */
  public void setBinSize(int binSize) {
    this.binSize = binSize;
  }
  
}
