package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * ExperimentLink generated by hbm2java
 */
public class ExperimentLink implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int experimentLinkId;
  private Experiment experiment;
  private String label;
  private String url;
  private String db;
  private String id;

  public ExperimentLink() {
  }

  public ExperimentLink(int experimentLinkId, Experiment experiment) {
    this.experimentLinkId = experimentLinkId;
    this.experiment = experiment;
  }

  public ExperimentLink(int experimentLinkId, Experiment experiment, String label, String url, String db, String id) {
    this.experimentLinkId = experimentLinkId;
    this.experiment = experiment;
    this.label = label;
    this.url = url;
    this.db = db;
    this.id = id;
  }

  public int getExperimentLinkId() {
    return this.experimentLinkId;
  }

  public void setExperimentLinkId(int experimentLinkId) {
    this.experimentLinkId = experimentLinkId;
  }

  public Experiment getExperiment() {
    return this.experiment;
  }

  public void setExperiment(Experiment experiment) {
    this.experiment = experiment;
  }

  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public String getUrl() {
    return this.url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public String getDb() {
    return this.db;
  }

  public void setDb(String db) {
    this.db = db;
  }

  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

}
