package net.sourceforge.seqware.common.model;

//default package

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * ExperimentAttribute generated by hbm2java
 */
public class ExperimentAttribute implements java.io.Serializable, Comparable<ExperimentAttribute> {

  private static final long serialVersionUID = 1L;
  private int experimentAttributeId;
  private Experiment experiment;
  private String tag;
  private String value;
  private String units;

  public ExperimentAttribute() {
  }

  public ExperimentAttribute(int experimentAttributeId, Experiment experiment) {
    this.experimentAttributeId = experimentAttributeId;
    this.experiment = experiment;
  }

  public ExperimentAttribute(int experimentAttributeId, Experiment experiment, String tag, String value, String units) {
    this.experimentAttributeId = experimentAttributeId;
    this.experiment = experiment;
    this.tag = tag;
    this.value = value;
    this.units = units;
  }

  public int getExperimentAttributeId() {
    return this.experimentAttributeId;
  }

  public void setExperimentAttributeId(int experimentAttributeId) {
    this.experimentAttributeId = experimentAttributeId;
  }

  public Experiment getExperiment() {
    return this.experiment;
  }

  public void setExperiment(Experiment experiment) {
    this.experiment = experiment;
  }

  public String getTag() {
    return this.tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public String getUnits() {
    return this.units;
  }

  public void setUnits(String units) {
    this.units = units;
  }

	@Override
	public int compareTo(ExperimentAttribute t) {
		return this.tag.compareTo(t.getTag());
	}

	@Override
	public boolean equals(Object obj) {
		if (obj instanceof ExperimentAttribute == false) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		ExperimentAttribute rhs = (ExperimentAttribute) obj;
		return new EqualsBuilder().appendSuper(super.equals(obj)).append(tag, rhs.getTag()).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(tag).toHashCode();
	}
}
