package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * ExperimentLink generated by hbm2java
 *
 * @author boconnor
 * @version $Id: $Id
 */
public class ExperimentLink implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int experimentLinkId;
  private Experiment experiment;
  private String label;
  private String url;
  private String db;
  private String id;

  /**
   * <p>Constructor for ExperimentLink.</p>
   */
  public ExperimentLink() {
  }

  /**
   * <p>Constructor for ExperimentLink.</p>
   *
   * @param experimentLinkId a int.
   * @param experiment a {@link net.sourceforge.seqware.common.model.Experiment} object.
   */
  public ExperimentLink(int experimentLinkId, Experiment experiment) {
    this.experimentLinkId = experimentLinkId;
    this.experiment = experiment;
  }

  /**
   * <p>Constructor for ExperimentLink.</p>
   *
   * @param experimentLinkId a int.
   * @param experiment a {@link net.sourceforge.seqware.common.model.Experiment} object.
   * @param label a {@link java.lang.String} object.
   * @param url a {@link java.lang.String} object.
   * @param db a {@link java.lang.String} object.
   * @param id a {@link java.lang.String} object.
   */
  public ExperimentLink(int experimentLinkId, Experiment experiment, String label, String url, String db, String id) {
    this.experimentLinkId = experimentLinkId;
    this.experiment = experiment;
    this.label = label;
    this.url = url;
    this.db = db;
    this.id = id;
  }

  /**
   * <p>Getter for the field <code>experimentLinkId</code>.</p>
   *
   * @return a int.
   */
  public int getExperimentLinkId() {
    return this.experimentLinkId;
  }

  /**
   * <p>Setter for the field <code>experimentLinkId</code>.</p>
   *
   * @param experimentLinkId a int.
   */
  public void setExperimentLinkId(int experimentLinkId) {
    this.experimentLinkId = experimentLinkId;
  }

  /**
   * <p>Getter for the field <code>experiment</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.common.model.Experiment} object.
   */
  public Experiment getExperiment() {
    return this.experiment;
  }

  /**
   * <p>Setter for the field <code>experiment</code>.</p>
   *
   * @param experiment a {@link net.sourceforge.seqware.common.model.Experiment} object.
   */
  public void setExperiment(Experiment experiment) {
    this.experiment = experiment;
  }

  /**
   * <p>Getter for the field <code>label</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getLabel() {
    return this.label;
  }

  /**
   * <p>Setter for the field <code>label</code>.</p>
   *
   * @param label a {@link java.lang.String} object.
   */
  public void setLabel(String label) {
    this.label = label;
  }

  /**
   * <p>Getter for the field <code>url</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getUrl() {
    return this.url;
  }

  /**
   * <p>Setter for the field <code>url</code>.</p>
   *
   * @param url a {@link java.lang.String} object.
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * <p>Getter for the field <code>db</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getDb() {
    return this.db;
  }

  /**
   * <p>Setter for the field <code>db</code>.</p>
   *
   * @param db a {@link java.lang.String} object.
   */
  public void setDb(String db) {
    this.db = db;
  }

  /**
   * <p>Getter for the field <code>id</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getId() {
    return this.id;
  }

  /**
   * <p>Setter for the field <code>id</code>.</p>
   *
   * @param id a {@link java.lang.String} object.
   */
  public void setId(String id) {
    this.id = id;
  }

}
