package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * IusAttribute generated by hbm2java
 */
public class IUSAttribute implements java.io.Serializable, Attribute, Comparable<IUSAttribute> {

  private static final long serialVersionUID = 1L;
  private Integer iusAttributeId;
  private IUS ius;
  private String tag;
  private String value;
  private String units;

  public IUSAttribute() {
  }

  public IUSAttribute(int iusAttributeId, IUS ius) {
    this.iusAttributeId = iusAttributeId;
    this.ius = ius;
  }

  public IUSAttribute(int iusAttributeId, IUS ius, String tag, String value, String units) {
    this.iusAttributeId = iusAttributeId;
    this.ius = ius;
    this.tag = tag;
    this.value = value;
    this.units = units;
  }

  public Integer getIusAttributeId() {
    return this.iusAttributeId;
  }

  public void setIusAttributeId(Integer iusAttributeId) {
    this.iusAttributeId = iusAttributeId;
  }

  public IUS getIus() {
    return this.ius;
  }

  public void setIus(IUS ius) {
    this.ius = ius;
  }

	@Override
  public String getTag() {
    return this.tag;
  }

	@Override
  public void setTag(String tag) {
    this.tag = tag;
  }

	@Override
  public String getValue() {
    return this.value;
  }

	@Override
  public void setValue(String value) {
    this.value = value;
  }

  public String getUnits() {
    return this.units;
  }

  public void setUnits(String units) {
    this.units = units;
  }

    @Override
    public String toString() {
        return "IUSAttribute{" + "iusAttributeId=" + iusAttributeId + ", tag=" + tag + ", value=" + value + ", units=" + units + '}';
    }

	@Override
	public String getUnit() {
		return this.getUnits();
	}

	@Override
	public void setUnit(String unit) {
		 this.setUnits(unit);
	}

	@Override
	public int compareTo(IUSAttribute t) {
		return this.tag.compareTo(t.tag);
	}


}
