package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * IusLink generated by hbm2java
 */
public class IUSLink implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int iusLinkId;
  private IUS ius;
  private String label;
  private String url;
  private String db;
  private String id;

  public IUSLink() {
  }

  public IUSLink(int iusLinkId, IUS ius, String label, String url) {
    this.iusLinkId = iusLinkId;
    this.ius = ius;
    this.label = label;
    this.url = url;
  }

  public IUSLink(int iusLinkId, IUS ius, String label, String url, String db, String id) {
    this.iusLinkId = iusLinkId;
    this.ius = ius;
    this.label = label;
    this.url = url;
    this.db = db;
    this.id = id;
  }

  public int getIusLinkId() {
    return this.iusLinkId;
  }

  public void setIusLinkId(int iusLinkId) {
    this.iusLinkId = iusLinkId;
  }

  public IUS getIus() {
    return this.ius;
  }

  public void setIus(IUS ius) {
    this.ius = ius;
  }

  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public String getUrl() {
    return this.url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public String getDb() {
    return this.db;
  }

  public void setDb(String db) {
    this.db = db;
  }

  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

}
