package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA
/**
 * LaneAttribute generated by hbm2java
 *
 * @author boconnor
 * @version $Id: $Id
 */
public class LaneAttribute implements java.io.Serializable, Comparable<LaneAttribute> {

    private static final long serialVersionUID = 1L;
    private Integer laneAttributeId;
    private Lane lane;
    private String tag;
    private String value;
    private String units;

    /**
     * <p>Constructor for LaneAttribute.</p>
     */
    public LaneAttribute() {
    }

    /**
     * <p>Constructor for LaneAttribute.</p>
     *
     * @param laneAttributeId a int.
     * @param lane a {@link net.sourceforge.seqware.common.model.Lane} object.
     */
    public LaneAttribute(int laneAttributeId, Lane lane) {
        this.laneAttributeId = laneAttributeId;
        this.lane = lane;
    }

    /**
     * <p>Constructor for LaneAttribute.</p>
     *
     * @param laneAttributeId a int.
     * @param lane a {@link net.sourceforge.seqware.common.model.Lane} object.
     * @param tag a {@link java.lang.String} object.
     * @param value a {@link java.lang.String} object.
     * @param units a {@link java.lang.String} object.
     */
    public LaneAttribute(int laneAttributeId, Lane lane, String tag, String value, String units) {
        this.laneAttributeId = laneAttributeId;
        this.lane = lane;
        this.tag = tag;
        this.value = value;
        this.units = units;
    }

    /**
     * <p>Getter for the field <code>laneAttributeId</code>.</p>
     *
     * @return a {@link java.lang.Integer} object.
     */
    public Integer getLaneAttributeId() {
        return this.laneAttributeId;
    }

    /**
     * <p>Setter for the field <code>laneAttributeId</code>.</p>
     *
     * @param laneAttributeId a {@link java.lang.Integer} object.
     */
    public void setLaneAttributeId(Integer laneAttributeId) {
        this.laneAttributeId = laneAttributeId;
    }

    /**
     * <p>Getter for the field <code>lane</code>.</p>
     *
     * @return a {@link net.sourceforge.seqware.common.model.Lane} object.
     */
    public Lane getLane() {
        return this.lane;
    }

    /**
     * <p>Setter for the field <code>lane</code>.</p>
     *
     * @param lane a {@link net.sourceforge.seqware.common.model.Lane} object.
     */
    public void setLane(Lane lane) {
        this.lane = lane;
    }

    /**
     * <p>Getter for the field <code>tag</code>.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String getTag() {
        return this.tag;
    }

    /**
     * <p>Setter for the field <code>tag</code>.</p>
     *
     * @param tag a {@link java.lang.String} object.
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * <p>Getter for the field <code>value</code>.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * <p>Setter for the field <code>value</code>.</p>
     *
     * @param value a {@link java.lang.String} object.
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * <p>Getter for the field <code>units</code>.</p>
     *
     * @return a {@link java.lang.String} object.
     */
    public String getUnits() {
        return this.units;
    }

    /**
     * <p>Setter for the field <code>units</code>.</p>
     *
     * @param units a {@link java.lang.String} object.
     */
    public void setUnits(String units) {
        this.units = units;
    }

    /** {@inheritDoc} */
    @Override
    public int compareTo(LaneAttribute t) {
        return t.getTag().compareTo(tag);
    }

    /** {@inheritDoc} */
    @Override
    public String toString() {
        return "LaneAttribute{" + "laneAttributeId=" + laneAttributeId + ", tag=" + tag + ", value=" + value + ", units=" + units + '}';
    }
    
}
