package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA
/**
 * LaneAttribute generated by hbm2java
 */
public class LaneAttribute implements java.io.Serializable, Comparable<LaneAttribute> {

    private static final long serialVersionUID = 1L;
    private Integer laneAttributeId;
    private Lane lane;
    private String tag;
    private String value;
    private String units;

    public LaneAttribute() {
    }

    public LaneAttribute(int laneAttributeId, Lane lane) {
        this.laneAttributeId = laneAttributeId;
        this.lane = lane;
    }

    public LaneAttribute(int laneAttributeId, Lane lane, String tag, String value, String units) {
        this.laneAttributeId = laneAttributeId;
        this.lane = lane;
        this.tag = tag;
        this.value = value;
        this.units = units;
    }

    public Integer getLaneAttributeId() {
        return this.laneAttributeId;
    }

    public void setLaneAttributeId(Integer laneAttributeId) {
        this.laneAttributeId = laneAttributeId;
    }

    public Lane getLane() {
        return this.lane;
    }

    public void setLane(Lane lane) {
        this.lane = lane;
    }

    public String getTag() {
        return this.tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getUnits() {
        return this.units;
    }

    public void setUnits(String units) {
        this.units = units;
    }

    @Override
    public int compareTo(LaneAttribute t) {
        return t.getTag().compareTo(tag);
    }

    @Override
    public String toString() {
        return "LaneAttribute{" + "laneAttributeId=" + laneAttributeId + ", tag=" + tag + ", value=" + value + ", units=" + units + '}';
    }
    
}
