package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * LaneLink generated by hbm2java
 *
 * @author boconnor
 * @version $Id: $Id
 */
public class LaneLink implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int laneLinkId;
  private Lane lane;
  private String label;
  private String url;
  private String db;
  private String id;

  /**
   * <p>Constructor for LaneLink.</p>
   */
  public LaneLink() {
  }

  /**
   * <p>Constructor for LaneLink.</p>
   *
   * @param laneLinkId a int.
   * @param lane a {@link net.sourceforge.seqware.common.model.Lane} object.
   * @param label a {@link java.lang.String} object.
   * @param url a {@link java.lang.String} object.
   */
  public LaneLink(int laneLinkId, Lane lane, String label, String url) {
    this.laneLinkId = laneLinkId;
    this.lane = lane;
    this.label = label;
    this.url = url;
  }

  /**
   * <p>Constructor for LaneLink.</p>
   *
   * @param laneLinkId a int.
   * @param lane a {@link net.sourceforge.seqware.common.model.Lane} object.
   * @param label a {@link java.lang.String} object.
   * @param url a {@link java.lang.String} object.
   * @param db a {@link java.lang.String} object.
   * @param id a {@link java.lang.String} object.
   */
  public LaneLink(int laneLinkId, Lane lane, String label, String url, String db, String id) {
    this.laneLinkId = laneLinkId;
    this.lane = lane;
    this.label = label;
    this.url = url;
    this.db = db;
    this.id = id;
  }

  /**
   * <p>Getter for the field <code>laneLinkId</code>.</p>
   *
   * @return a int.
   */
  public int getLaneLinkId() {
    return this.laneLinkId;
  }

  /**
   * <p>Setter for the field <code>laneLinkId</code>.</p>
   *
   * @param laneLinkId a int.
   */
  public void setLaneLinkId(int laneLinkId) {
    this.laneLinkId = laneLinkId;
  }

  /**
   * <p>Getter for the field <code>lane</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.common.model.Lane} object.
   */
  public Lane getLane() {
    return this.lane;
  }

  /**
   * <p>Setter for the field <code>lane</code>.</p>
   *
   * @param lane a {@link net.sourceforge.seqware.common.model.Lane} object.
   */
  public void setLane(Lane lane) {
    this.lane = lane;
  }

  /**
   * <p>Getter for the field <code>label</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getLabel() {
    return this.label;
  }

  /**
   * <p>Setter for the field <code>label</code>.</p>
   *
   * @param label a {@link java.lang.String} object.
   */
  public void setLabel(String label) {
    this.label = label;
  }

  /**
   * <p>Getter for the field <code>url</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getUrl() {
    return this.url;
  }

  /**
   * <p>Setter for the field <code>url</code>.</p>
   *
   * @param url a {@link java.lang.String} object.
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * <p>Getter for the field <code>db</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getDb() {
    return this.db;
  }

  /**
   * <p>Setter for the field <code>db</code>.</p>
   *
   * @param db a {@link java.lang.String} object.
   */
  public void setDb(String db) {
    this.db = db;
  }

  /**
   * <p>Getter for the field <code>id</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getId() {
    return this.id;
  }

  /**
   * <p>Setter for the field <code>id</code>.</p>
   *
   * @param id a {@link java.lang.String} object.
   */
  public void setId(String id) {
    this.id = id;
  }

}
