package net.sourceforge.seqware.common.model;

//default package

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * ProcessingAttribute generated by hbm2java
 *
 * @author boconnor
 * @version $Id: $Id
 */
public class ProcessingAttribute implements java.io.Serializable, Comparable<ProcessingAttribute>, Attribute {

  private static final long serialVersionUID = 1L;
  private int processingAttributeId;
  private Processing processing;
  private String tag;
  private String value;
  private String units;

  /**
   * <p>Constructor for ProcessingAttribute.</p>
   */
  public ProcessingAttribute() {
  }

  /**
   * <p>Constructor for ProcessingAttribute.</p>
   *
   * @param processingAttributeId a int.
   * @param processing a {@link net.sourceforge.seqware.common.model.Processing} object.
   */
  public ProcessingAttribute(int processingAttributeId, Processing processing) {
    this.processingAttributeId = processingAttributeId;
    this.processing = processing;
  }

  /**
   * <p>Constructor for ProcessingAttribute.</p>
   *
   * @param processingAttributeId a int.
   * @param processing a {@link net.sourceforge.seqware.common.model.Processing} object.
   * @param tag a {@link java.lang.String} object.
   * @param value a {@link java.lang.String} object.
   * @param units a {@link java.lang.String} object.
   */
  public ProcessingAttribute(int processingAttributeId, Processing processing, String tag, String value, String units) {
    this.processingAttributeId = processingAttributeId;
    this.processing = processing;
    this.tag = tag;
    this.value = value;
    this.units = units;
  }

  /**
   * <p>Getter for the field <code>processingAttributeId</code>.</p>
   *
   * @return a int.
   */
  public int getProcessingAttributeId() {
    return this.processingAttributeId;
  }

  /**
   * <p>Setter for the field <code>processingAttributeId</code>.</p>
   *
   * @param processingAttributeId a int.
   */
  public void setProcessingAttributeId(int processingAttributeId) {
    this.processingAttributeId = processingAttributeId;
  }

  /**
   * <p>Getter for the field <code>processing</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.common.model.Processing} object.
   */
  public Processing getProcessing() {
    return this.processing;
  }

  /**
   * <p>Setter for the field <code>processing</code>.</p>
   *
   * @param processing a {@link net.sourceforge.seqware.common.model.Processing} object.
   */
  public void setProcessing(Processing processing) {
    this.processing = processing;
  }

	/** {@inheritDoc} */
	@Override
  public String getTag() {
    return this.tag;
  }

	/** {@inheritDoc} */
	@Override
  public void setTag(String tag) {
    this.tag = tag;
  }

	/** {@inheritDoc} */
	@Override
  public String getValue() {
    return this.value;
  }

	/** {@inheritDoc} */
	@Override
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * <p>Getter for the field <code>units</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getUnits() {
    return this.units;
  }

  /**
   * <p>Setter for the field <code>units</code>.</p>
   *
   * @param units a {@link java.lang.String} object.
   */
  public void setUnits(String units) {
    this.units = units;
  }

	/** {@inheritDoc} */
	@Override
	public int compareTo(ProcessingAttribute t) {
		return this.tag.compareTo(t.getTag());
	}

	/** {@inheritDoc} */
	@Override
	public boolean equals(Object obj) {
		if(obj instanceof ProcessingAttribute == false)
			return false;
		if( obj == this)
			return true;
		ProcessingAttribute rhs = (ProcessingAttribute) obj;
		return new EqualsBuilder().appendSuper(super.equals(obj)).append(rhs.getTag(), tag).isEquals();
	}

	/** {@inheritDoc} */
	@Override
	public int hashCode() {
		return new HashCodeBuilder(17,37).append(tag).toHashCode();
	}

	/** {@inheritDoc} */
	@Override
	public String getUnit() {
		return this.units;
	}

	/** {@inheritDoc} */
	@Override
	public void setUnit(String unit) {
		this.units = unit;
	}

}
