package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * ProcessingStudies generated by hbm2java
 */
public class ProcessingStudies implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int processingStudiesId;
  private Processing processing;
  private Study study;
  private String description;
  private String label;
  private String url;
  private Integer swAccession;

  public ProcessingStudies() {
  }

  public ProcessingStudies(int processingStudiesId, Processing processing, Study study) {
    this.processingStudiesId = processingStudiesId;
    this.processing = processing;
    this.study = study;
  }

  public ProcessingStudies(int processingStudiesId, Processing processing, Study study, String description,
      String label, String url, Integer swAccession) {
    this.processingStudiesId = processingStudiesId;
    this.processing = processing;
    this.study = study;
    this.description = description;
    this.label = label;
    this.url = url;
    this.swAccession = swAccession;
  }

  public int getProcessingStudiesId() {
    return this.processingStudiesId;
  }

  public void setProcessingStudiesId(int processingStudiesId) {
    this.processingStudiesId = processingStudiesId;
  }

  public Processing getProcessing() {
    return this.processing;
  }

  public void setProcessing(Processing processing) {
    this.processing = processing;
  }

  public Study getStudy() {
    return this.study;
  }

  public void setStudy(Study study) {
    this.study = study;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public String getUrl() {
    return this.url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Integer getSwAccession() {
    return this.swAccession;
  }

  public void setSwAccession(Integer swAccession) {
    this.swAccession = swAccession;
  }

}
