package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * ProcessingSequencerRuns generated by hbm2java
 *
 * @author boconnor
 * @version $Id: $Id
 */
public class ProcessingSequencerRuns implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int processingSequencerRunsId;
  private Processing processing;
  private SequencerRun sequencerRun;
  private String description;
  private String label;
  private String url;
  private Integer swAccession;

  /**
   * <p>Constructor for ProcessingSequencerRuns.</p>
   */
  public ProcessingSequencerRuns() {
  }

  /**
   * <p>Constructor for ProcessingSequencerRuns.</p>
   *
   * @param processingSequencerRunsId a int.
   * @param processing a {@link net.sourceforge.seqware.common.model.Processing} object.
   * @param sequencerRun a {@link net.sourceforge.seqware.common.model.SequencerRun} object.
   */
  public ProcessingSequencerRuns(int processingSequencerRunsId, Processing processing, SequencerRun sequencerRun) {
    this.processingSequencerRunsId = processingSequencerRunsId;
    this.processing = processing;
    this.sequencerRun = sequencerRun;
  }

  /**
   * <p>Constructor for ProcessingSequencerRuns.</p>
   *
   * @param processingSequencerRunsId a int.
   * @param processing a {@link net.sourceforge.seqware.common.model.Processing} object.
   * @param sequencerRun a {@link net.sourceforge.seqware.common.model.SequencerRun} object.
   * @param description a {@link java.lang.String} object.
   * @param label a {@link java.lang.String} object.
   * @param url a {@link java.lang.String} object.
   * @param swAccession a {@link java.lang.Integer} object.
   */
  public ProcessingSequencerRuns(int processingSequencerRunsId, Processing processing, SequencerRun sequencerRun,
      String description, String label, String url, Integer swAccession) {
    this.processingSequencerRunsId = processingSequencerRunsId;
    this.processing = processing;
    this.sequencerRun = sequencerRun;
    this.description = description;
    this.label = label;
    this.url = url;
    this.swAccession = swAccession;
  }

  /**
   * <p>Getter for the field <code>processingSequencerRunsId</code>.</p>
   *
   * @return a int.
   */
  public int getProcessingSequencerRunsId() {
    return this.processingSequencerRunsId;
  }

  /**
   * <p>Setter for the field <code>processingSequencerRunsId</code>.</p>
   *
   * @param processingSequencerRunsId a int.
   */
  public void setProcessingSequencerRunsId(int processingSequencerRunsId) {
    this.processingSequencerRunsId = processingSequencerRunsId;
  }

  /**
   * <p>Getter for the field <code>processing</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.common.model.Processing} object.
   */
  public Processing getProcessing() {
    return this.processing;
  }

  /**
   * <p>Setter for the field <code>processing</code>.</p>
   *
   * @param processing a {@link net.sourceforge.seqware.common.model.Processing} object.
   */
  public void setProcessing(Processing processing) {
    this.processing = processing;
  }

  /**
   * <p>Getter for the field <code>sequencerRun</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.common.model.SequencerRun} object.
   */
  public SequencerRun getSequencerRun() {
    return this.sequencerRun;
  }

  /**
   * <p>Setter for the field <code>sequencerRun</code>.</p>
   *
   * @param sequencerRun a {@link net.sourceforge.seqware.common.model.SequencerRun} object.
   */
  public void setSequencerRun(SequencerRun sequencerRun) {
    this.sequencerRun = sequencerRun;
  }

  /**
   * <p>Getter for the field <code>description</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getDescription() {
    return this.description;
  }

  /**
   * <p>Setter for the field <code>description</code>.</p>
   *
   * @param description a {@link java.lang.String} object.
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * <p>Getter for the field <code>label</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getLabel() {
    return this.label;
  }

  /**
   * <p>Setter for the field <code>label</code>.</p>
   *
   * @param label a {@link java.lang.String} object.
   */
  public void setLabel(String label) {
    this.label = label;
  }

  /**
   * <p>Getter for the field <code>url</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getUrl() {
    return this.url;
  }

  /**
   * <p>Setter for the field <code>url</code>.</p>
   *
   * @param url a {@link java.lang.String} object.
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   * <p>Getter for the field <code>swAccession</code>.</p>
   *
   * @return a {@link java.lang.Integer} object.
   */
  public Integer getSwAccession() {
    return this.swAccession;
  }

  /**
   * <p>Setter for the field <code>swAccession</code>.</p>
   *
   * @param swAccession a {@link java.lang.Integer} object.
   */
  public void setSwAccession(Integer swAccession) {
    this.swAccession = swAccession;
  }

}
