package net.sourceforge.seqware.common.model;

/**
 * ProcessingSamples generated by hbm2java
 */
public class ProcessingSamples implements java.io.Serializable {

  private static final long serialVersionUID = -1L;
  private int processingSamplesId;
  private Processing processing;
  private Sample sample;
  private String description;
  private String label;
  private String url;
  private Integer swAccession;

  public ProcessingSamples() {
  }

  public ProcessingSamples(int processingSamplesId, Processing processing, Sample sample) {
    this.processingSamplesId = processingSamplesId;
    this.processing = processing;
    this.sample = sample;
  }

  public ProcessingSamples(int processingSamplesId, Processing processing, Sample sample, String description,
      String label, String url, Integer swAccession) {
    this.processingSamplesId = processingSamplesId;
    this.processing = processing;
    this.sample = sample;
    this.description = description;
    this.label = label;
    this.url = url;
    this.swAccession = swAccession;
  }

  public int getProcessingSamplesId() {
    return this.processingSamplesId;
  }

  public void setProcessingSamplesId(int processingSamplesId) {
    this.processingSamplesId = processingSamplesId;
  }

  public Processing getProcessing() {
    return this.processing;
  }

  public void setProcessing(Processing processing) {
    this.processing = processing;
  }

  public Sample getSample() {
    return this.sample;
  }

  public void setSample(Sample sample) {
    this.sample = sample;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public String getUrl() {
    return this.url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Integer getSwAccession() {
    return this.swAccession;
  }

  public void setSwAccession(Integer swAccession) {
    this.swAccession = swAccession;
  }

}
