package net.sourceforge.seqware.common.model;

/**
 * ProcessingRelationship generated by hbm2java
 */
public class ProcessingRelationship implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int processingRelationshipId;
  private Processing processingByParentId;
  private Processing processingByChildId;
  private String relationship;

  public ProcessingRelationship() {
  }

  public ProcessingRelationship(int processingRelationshipId) {
    this.processingRelationshipId = processingRelationshipId;
  }

  public ProcessingRelationship(int processingRelationshipId, Processing processingByParentId,
      Processing processingByChildId, String relationship) {
    this.processingRelationshipId = processingRelationshipId;
    this.processingByParentId = processingByParentId;
    this.processingByChildId = processingByChildId;
    this.relationship = relationship;
  }

  public int getProcessingRelationshipId() {
    return this.processingRelationshipId;
  }

  public void setProcessingRelationshipId(int processingRelationshipId) {
    this.processingRelationshipId = processingRelationshipId;
  }

  public Processing getProcessingByParentId() {
    return this.processingByParentId;
  }

  public void setProcessingByParentId(Processing processingByParentId) {
    this.processingByParentId = processingByParentId;
  }

  public Processing getProcessingByChildId() {
    return this.processingByChildId;
  }

  public void setProcessingByChildId(Processing processingByChildId) {
    this.processingByChildId = processingByChildId;
  }

  public String getRelationship() {
    return this.relationship;
  }

  public void setRelationship(String relationship) {
    this.relationship = relationship;
  }

}
