package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * SampleLink generated by hbm2java
 */
public class SampleLink implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int sampleLinkId;
  private Sample sample;
  private String label;
  private String url;
  private String db;
  private String id;

  public SampleLink() {
  }

  public SampleLink(int sampleLinkId, Sample sample, String label, String url) {
    this.sampleLinkId = sampleLinkId;
    this.sample = sample;
    this.label = label;
    this.url = url;
  }

  public SampleLink(int sampleLinkId, Sample sample, String label, String url, String db, String id) {
    this.sampleLinkId = sampleLinkId;
    this.sample = sample;
    this.label = label;
    this.url = url;
    this.db = db;
    this.id = id;
  }

  public int getSampleLinkId() {
    return this.sampleLinkId;
  }

  public void setSampleLinkId(int sampleLinkId) {
    this.sampleLinkId = sampleLinkId;
  }

  public Sample getSample() {
    return this.sample;
  }

  public void setSample(Sample sample) {
    this.sample = sample;
  }

  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public String getUrl() {
    return this.url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public String getDb() {
    return this.db;
  }

  public void setDb(String db) {
    this.db = db;
  }

  public String getId() {
    return this.id;
  }

  public void setId(String id) {
    this.id = id;
  }

}
