package net.sourceforge.seqware.common.model;

//default package

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * SampleAttribute generated by hbm2java
 *
 * @author boconnor
 * @version $Id: $Id
 */
public class SampleAttribute implements java.io.Serializable, Attribute, Comparable<SampleAttribute> {

  private static final long serialVersionUID = 1L;
  private int sampleAttributeId;
  private Sample sample;
  private String tag;
  private String value;
  private String units;

  /**
   * <p>Constructor for SampleAttribute.</p>
   */
  public SampleAttribute() {
  }

  /**
   * <p>Constructor for SampleAttribute.</p>
   *
   * @param sampleAttributeId a int.
   * @param sample a {@link net.sourceforge.seqware.common.model.Sample} object.
   * @param tag a {@link java.lang.String} object.
   * @param value a {@link java.lang.String} object.
   */
  public SampleAttribute(int sampleAttributeId, Sample sample, String tag, String value) {
    this.sampleAttributeId = sampleAttributeId;
    this.sample = sample;
    this.tag = tag;
    this.value = value;
  }

  /**
   * <p>Constructor for SampleAttribute.</p>
   *
   * @param sampleAttributeId a int.
   * @param sample a {@link net.sourceforge.seqware.common.model.Sample} object.
   * @param tag a {@link java.lang.String} object.
   * @param value a {@link java.lang.String} object.
   * @param units a {@link java.lang.String} object.
   */
  public SampleAttribute(int sampleAttributeId, Sample sample, String tag, String value, String units) {
    this.sampleAttributeId = sampleAttributeId;
    this.sample = sample;
    this.tag = tag;
    this.value = value;
    this.units = units;
  }

  /**
   * <p>Getter for the field <code>sampleAttributeId</code>.</p>
   *
   * @return a int.
   */
  public int getSampleAttributeId() {
    return this.sampleAttributeId;
  }

  /**
   * <p>Setter for the field <code>sampleAttributeId</code>.</p>
   *
   * @param sampleAttributeId a int.
   */
  public void setSampleAttributeId(int sampleAttributeId) {
    this.sampleAttributeId = sampleAttributeId;
  }

  /**
   * <p>Getter for the field <code>sample</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.common.model.Sample} object.
   */
  public Sample getSample() {
    return this.sample;
  }

  /**
   * <p>Setter for the field <code>sample</code>.</p>
   *
   * @param sample a {@link net.sourceforge.seqware.common.model.Sample} object.
   */
  public void setSample(Sample sample) {
    this.sample = sample;
  }

	/** {@inheritDoc} */
	@Override
  public String getTag() {
    return this.tag;
  }

	/** {@inheritDoc} */
	@Override
  public void setTag(String tag) {
    this.tag = tag;
  }

	/** {@inheritDoc} */
	@Override
  public String getValue() {
    return this.value;
  }

	/** {@inheritDoc} */
	@Override
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * <p>Getter for the field <code>units</code>.</p>
   *
   * @return a {@link java.lang.String} object.
   */
  public String getUnits() {
    return this.units;
  }

  /**
   * <p>Setter for the field <code>units</code>.</p>
   *
   * @param units a {@link java.lang.String} object.
   */
  public void setUnits(String units) {
    this.units = units;
  }

	/** {@inheritDoc} */
	@Override
	public String getUnit() {
		return this.getUnits();
	}

	/** {@inheritDoc} */
	@Override
	public void setUnit(String unit) {
		this.setUnits(unit);
	}

	/** {@inheritDoc} */
	@Override
	public int compareTo(SampleAttribute t) {
		return tag.compareTo(t.tag);
	}

	/** {@inheritDoc} */
	@Override
	public boolean equals(Object obj) {
		if(obj instanceof SampleAttribute == false)
			return false;
		if(obj == this)
			return true;
		SampleAttribute rhs = (SampleAttribute) obj;
		return new EqualsBuilder().appendSuper(super.equals(obj)).append(tag, rhs.tag).isEquals();
	}

	/** {@inheritDoc} */
	@Override
	public int hashCode() {
		return new HashCodeBuilder(17,37).append(tag).toHashCode();
	}

}
