package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ShareProcessing generated by hbm2java
 */
public class ShareProcessing implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int shareProcessingId;
  private Processing processing;
  private Registration registration;
  private Boolean active;
  private Integer swAccession;
  private Date createTstmp;
  private Date updateTstmp;

  public ShareProcessing() {
  }

  public ShareProcessing(int shareProcessingId, Processing processing, Registration registration, Date createTstmp) {
    this.shareProcessingId = shareProcessingId;
    this.processing = processing;
    this.registration = registration;
    this.createTstmp = createTstmp;
  }

  public ShareProcessing(int shareProcessingId, Processing processing, Registration registration, Boolean active,
      Integer swAccession, Date createTstmp, Date updateTstmp) {
    this.shareProcessingId = shareProcessingId;
    this.processing = processing;
    this.registration = registration;
    this.active = active;
    this.swAccession = swAccession;
    this.createTstmp = createTstmp;
    this.updateTstmp = updateTstmp;
  }

  public int getShareProcessingId() {
    return this.shareProcessingId;
  }

  public void setShareProcessingId(int shareProcessingId) {
    this.shareProcessingId = shareProcessingId;
  }

  public Processing getProcessing() {
    return this.processing;
  }

  public void setProcessing(Processing processing) {
    this.processing = processing;
  }

  public Registration getRegistration() {
    return this.registration;
  }

  public void setRegistration(Registration registration) {
    this.registration = registration;
  }

  public Boolean getActive() {
    return this.active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Integer getSwAccession() {
    return this.swAccession;
  }

  public void setSwAccession(Integer swAccession) {
    this.swAccession = swAccession;
  }

  public Date getCreateTstmp() {
    return this.createTstmp;
  }

  public void setCreateTstmp(Date createTstmp) {
    this.createTstmp = createTstmp;
  }

  public Date getUpdateTstmp() {
    return this.updateTstmp;
  }

  public void setUpdateTstmp(Date updateTstmp) {
    this.updateTstmp = updateTstmp;
  }

}
