package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ShareFile generated by hbm2java
 *
 * @author boconnor
 * @version $Id: $Id
 */
public class ShareFile implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int shareFileId;
  private File file;
  private Registration registration;
  private Boolean active;
  private Integer swAccession;
  private Date createTstmp;
  private Date updateTstmp;

  /**
   * <p>Constructor for ShareFile.</p>
   */
  public ShareFile() {
  }

  /**
   * <p>Constructor for ShareFile.</p>
   *
   * @param shareFileId a int.
   * @param file a {@link net.sourceforge.seqware.common.model.File} object.
   * @param registration a {@link net.sourceforge.seqware.common.model.Registration} object.
   * @param createTstmp a {@link java.util.Date} object.
   */
  public ShareFile(int shareFileId, File file, Registration registration, Date createTstmp) {
    this.shareFileId = shareFileId;
    this.file = file;
    this.registration = registration;
    this.createTstmp = createTstmp;
  }

  /**
   * <p>Constructor for ShareFile.</p>
   *
   * @param shareFileId a int.
   * @param file a {@link net.sourceforge.seqware.common.model.File} object.
   * @param registration a {@link net.sourceforge.seqware.common.model.Registration} object.
   * @param active a {@link java.lang.Boolean} object.
   * @param swAccession a {@link java.lang.Integer} object.
   * @param createTstmp a {@link java.util.Date} object.
   * @param updateTstmp a {@link java.util.Date} object.
   */
  public ShareFile(int shareFileId, File file, Registration registration, Boolean active, Integer swAccession,
      Date createTstmp, Date updateTstmp) {
    this.shareFileId = shareFileId;
    this.file = file;
    this.registration = registration;
    this.active = active;
    this.swAccession = swAccession;
    this.createTstmp = createTstmp;
    this.updateTstmp = updateTstmp;
  }

  /**
   * <p>Getter for the field <code>shareFileId</code>.</p>
   *
   * @return a int.
   */
  public int getShareFileId() {
    return this.shareFileId;
  }

  /**
   * <p>Setter for the field <code>shareFileId</code>.</p>
   *
   * @param shareFileId a int.
   */
  public void setShareFileId(int shareFileId) {
    this.shareFileId = shareFileId;
  }

  /**
   * <p>Getter for the field <code>file</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.common.model.File} object.
   */
  public File getFile() {
    return this.file;
  }

  /**
   * <p>Setter for the field <code>file</code>.</p>
   *
   * @param file a {@link net.sourceforge.seqware.common.model.File} object.
   */
  public void setFile(File file) {
    this.file = file;
  }

  /**
   * <p>Getter for the field <code>registration</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.common.model.Registration} object.
   */
  public Registration getRegistration() {
    return this.registration;
  }

  /**
   * <p>Setter for the field <code>registration</code>.</p>
   *
   * @param registration a {@link net.sourceforge.seqware.common.model.Registration} object.
   */
  public void setRegistration(Registration registration) {
    this.registration = registration;
  }

  /**
   * <p>Getter for the field <code>active</code>.</p>
   *
   * @return a {@link java.lang.Boolean} object.
   */
  public Boolean getActive() {
    return this.active;
  }

  /**
   * <p>Setter for the field <code>active</code>.</p>
   *
   * @param active a {@link java.lang.Boolean} object.
   */
  public void setActive(Boolean active) {
    this.active = active;
  }

  /**
   * <p>Getter for the field <code>swAccession</code>.</p>
   *
   * @return a {@link java.lang.Integer} object.
   */
  public Integer getSwAccession() {
    return this.swAccession;
  }

  /**
   * <p>Setter for the field <code>swAccession</code>.</p>
   *
   * @param swAccession a {@link java.lang.Integer} object.
   */
  public void setSwAccession(Integer swAccession) {
    this.swAccession = swAccession;
  }

  /**
   * <p>Getter for the field <code>createTstmp</code>.</p>
   *
   * @return a {@link java.util.Date} object.
   */
  public Date getCreateTstmp() {
    return this.createTstmp;
  }

  /**
   * <p>Setter for the field <code>createTstmp</code>.</p>
   *
   * @param createTstmp a {@link java.util.Date} object.
   */
  public void setCreateTstmp(Date createTstmp) {
    this.createTstmp = createTstmp;
  }

  /**
   * <p>Getter for the field <code>updateTstmp</code>.</p>
   *
   * @return a {@link java.util.Date} object.
   */
  public Date getUpdateTstmp() {
    return this.updateTstmp;
  }

  /**
   * <p>Setter for the field <code>updateTstmp</code>.</p>
   *
   * @param updateTstmp a {@link java.util.Date} object.
   */
  public void setUpdateTstmp(Date updateTstmp) {
    this.updateTstmp = updateTstmp;
  }

}
