package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ShareLane generated by hbm2java
 */
public class ShareLane implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int shareLaneId;
  private Lane lane;
  private Registration registration;
  private Boolean active;
  private Integer swAccession;
  private Date createTstmp;
  private Date updateTstmp;

  public ShareLane() {
  }

  public ShareLane(int shareLaneId, Lane lane, Registration registration, Date createTstmp) {
    this.shareLaneId = shareLaneId;
    this.lane = lane;
    this.registration = registration;
    this.createTstmp = createTstmp;
  }

  public ShareLane(int shareLaneId, Lane lane, Registration registration, Boolean active, Integer swAccession,
      Date createTstmp, Date updateTstmp) {
    this.shareLaneId = shareLaneId;
    this.lane = lane;
    this.registration = registration;
    this.active = active;
    this.swAccession = swAccession;
    this.createTstmp = createTstmp;
    this.updateTstmp = updateTstmp;
  }

  public int getShareLaneId() {
    return this.shareLaneId;
  }

  public void setShareLaneId(int shareLaneId) {
    this.shareLaneId = shareLaneId;
  }

  public Lane getLane() {
    return this.lane;
  }

  public void setLane(Lane lane) {
    this.lane = lane;
  }

  public Registration getRegistration() {
    return this.registration;
  }

  public void setRegistration(Registration registration) {
    this.registration = registration;
  }

  public Boolean getActive() {
    return this.active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Integer getSwAccession() {
    return this.swAccession;
  }

  public void setSwAccession(Integer swAccession) {
    this.swAccession = swAccession;
  }

  public Date getCreateTstmp() {
    return this.createTstmp;
  }

  public void setCreateTstmp(Date createTstmp) {
    this.createTstmp = createTstmp;
  }

  public Date getUpdateTstmp() {
    return this.updateTstmp;
  }

  public void setUpdateTstmp(Date updateTstmp) {
    this.updateTstmp = updateTstmp;
  }

}
