package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ShareFile generated by hbm2java
 */
public class ShareFile implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int shareFileId;
  private File file;
  private Registration registration;
  private Boolean active;
  private Integer swAccession;
  private Date createTstmp;
  private Date updateTstmp;

  public ShareFile() {
  }

  public ShareFile(int shareFileId, File file, Registration registration, Date createTstmp) {
    this.shareFileId = shareFileId;
    this.file = file;
    this.registration = registration;
    this.createTstmp = createTstmp;
  }

  public ShareFile(int shareFileId, File file, Registration registration, Boolean active, Integer swAccession,
      Date createTstmp, Date updateTstmp) {
    this.shareFileId = shareFileId;
    this.file = file;
    this.registration = registration;
    this.active = active;
    this.swAccession = swAccession;
    this.createTstmp = createTstmp;
    this.updateTstmp = updateTstmp;
  }

  public int getShareFileId() {
    return this.shareFileId;
  }

  public void setShareFileId(int shareFileId) {
    this.shareFileId = shareFileId;
  }

  public File getFile() {
    return this.file;
  }

  public void setFile(File file) {
    this.file = file;
  }

  public Registration getRegistration() {
    return this.registration;
  }

  public void setRegistration(Registration registration) {
    this.registration = registration;
  }

  public Boolean getActive() {
    return this.active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Integer getSwAccession() {
    return this.swAccession;
  }

  public void setSwAccession(Integer swAccession) {
    this.swAccession = swAccession;
  }

  public Date getCreateTstmp() {
    return this.createTstmp;
  }

  public void setCreateTstmp(Date createTstmp) {
    this.createTstmp = createTstmp;
  }

  public Date getUpdateTstmp() {
    return this.updateTstmp;
  }

  public void setUpdateTstmp(Date updateTstmp) {
    this.updateTstmp = updateTstmp;
  }

}
