package net.sourceforge.seqware.common.model;

//default package
//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ShareProcessing generated by hbm2java
 *
 * @author boconnor
 * @version $Id: $Id
 */
public class ShareProcessing implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  private int shareProcessingId;
  private Processing processing;
  private Registration registration;
  private Boolean active;
  private Integer swAccession;
  private Date createTstmp;
  private Date updateTstmp;

  /**
   * <p>Constructor for ShareProcessing.</p>
   */
  public ShareProcessing() {
  }

  /**
   * <p>Constructor for ShareProcessing.</p>
   *
   * @param shareProcessingId a int.
   * @param processing a {@link net.sourceforge.seqware.common.model.Processing} object.
   * @param registration a {@link net.sourceforge.seqware.common.model.Registration} object.
   * @param createTstmp a {@link java.util.Date} object.
   */
  public ShareProcessing(int shareProcessingId, Processing processing, Registration registration, Date createTstmp) {
    this.shareProcessingId = shareProcessingId;
    this.processing = processing;
    this.registration = registration;
    this.createTstmp = createTstmp;
  }

  /**
   * <p>Constructor for ShareProcessing.</p>
   *
   * @param shareProcessingId a int.
   * @param processing a {@link net.sourceforge.seqware.common.model.Processing} object.
   * @param registration a {@link net.sourceforge.seqware.common.model.Registration} object.
   * @param active a {@link java.lang.Boolean} object.
   * @param swAccession a {@link java.lang.Integer} object.
   * @param createTstmp a {@link java.util.Date} object.
   * @param updateTstmp a {@link java.util.Date} object.
   */
  public ShareProcessing(int shareProcessingId, Processing processing, Registration registration, Boolean active,
      Integer swAccession, Date createTstmp, Date updateTstmp) {
    this.shareProcessingId = shareProcessingId;
    this.processing = processing;
    this.registration = registration;
    this.active = active;
    this.swAccession = swAccession;
    this.createTstmp = createTstmp;
    this.updateTstmp = updateTstmp;
  }

  /**
   * <p>Getter for the field <code>shareProcessingId</code>.</p>
   *
   * @return a int.
   */
  public int getShareProcessingId() {
    return this.shareProcessingId;
  }

  /**
   * <p>Setter for the field <code>shareProcessingId</code>.</p>
   *
   * @param shareProcessingId a int.
   */
  public void setShareProcessingId(int shareProcessingId) {
    this.shareProcessingId = shareProcessingId;
  }

  /**
   * <p>Getter for the field <code>processing</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.common.model.Processing} object.
   */
  public Processing getProcessing() {
    return this.processing;
  }

  /**
   * <p>Setter for the field <code>processing</code>.</p>
   *
   * @param processing a {@link net.sourceforge.seqware.common.model.Processing} object.
   */
  public void setProcessing(Processing processing) {
    this.processing = processing;
  }

  /**
   * <p>Getter for the field <code>registration</code>.</p>
   *
   * @return a {@link net.sourceforge.seqware.common.model.Registration} object.
   */
  public Registration getRegistration() {
    return this.registration;
  }

  /**
   * <p>Setter for the field <code>registration</code>.</p>
   *
   * @param registration a {@link net.sourceforge.seqware.common.model.Registration} object.
   */
  public void setRegistration(Registration registration) {
    this.registration = registration;
  }

  /**
   * <p>Getter for the field <code>active</code>.</p>
   *
   * @return a {@link java.lang.Boolean} object.
   */
  public Boolean getActive() {
    return this.active;
  }

  /**
   * <p>Setter for the field <code>active</code>.</p>
   *
   * @param active a {@link java.lang.Boolean} object.
   */
  public void setActive(Boolean active) {
    this.active = active;
  }

  /**
   * <p>Getter for the field <code>swAccession</code>.</p>
   *
   * @return a {@link java.lang.Integer} object.
   */
  public Integer getSwAccession() {
    return this.swAccession;
  }

  /**
   * <p>Setter for the field <code>swAccession</code>.</p>
   *
   * @param swAccession a {@link java.lang.Integer} object.
   */
  public void setSwAccession(Integer swAccession) {
    this.swAccession = swAccession;
  }

  /**
   * <p>Getter for the field <code>createTstmp</code>.</p>
   *
   * @return a {@link java.util.Date} object.
   */
  public Date getCreateTstmp() {
    return this.createTstmp;
  }

  /**
   * <p>Setter for the field <code>createTstmp</code>.</p>
   *
   * @param createTstmp a {@link java.util.Date} object.
   */
  public void setCreateTstmp(Date createTstmp) {
    this.createTstmp = createTstmp;
  }

  /**
   * <p>Getter for the field <code>updateTstmp</code>.</p>
   *
   * @return a {@link java.util.Date} object.
   */
  public Date getUpdateTstmp() {
    return this.updateTstmp;
  }

  /**
   * <p>Setter for the field <code>updateTstmp</code>.</p>
   *
   * @param updateTstmp a {@link java.util.Date} object.
   */
  public void setUpdateTstmp(Date updateTstmp) {
    this.updateTstmp = updateTstmp;
  }

}
