package net.sourceforge.seqware.common.model;

//default package

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

//Generated 09.12.2011 15:01:20 by Hibernate Tools 3.2.4.GA

/**
 * StudyAttribute generated by hbm2java
 */
public class StudyAttribute implements java.io.Serializable, Comparable<StudyAttribute>, Attribute {

  private static final long serialVersionUID = 1L;
  private int studyAttributeId;
  private Study study;
  private String tag;
  private String value;
  private String units;

  public StudyAttribute() {
  }

  public StudyAttribute(int studyAttributeId, Study study, String tag, String value) {
    this.studyAttributeId = studyAttributeId;
    this.study = study;
    this.tag = tag;
    this.value = value;
  }

  public StudyAttribute(int studyAttributeId, Study study, String tag, String value, String units) {
    this.studyAttributeId = studyAttributeId;
    this.study = study;
    this.tag = tag;
    this.value = value;
    this.units = units;
  }

  public int getStudyAttributeId() {
    return this.studyAttributeId;
  }

  public void setStudyAttributeId(int studyAttributeId) {
    this.studyAttributeId = studyAttributeId;
  }

  public Study getStudy() {
    return this.study;
  }

  public void setStudy(Study study) {
    this.study = study;
  }

	@Override
  public String getTag() {
    return this.tag;
  }

	@Override
  public void setTag(String tag) {
    this.tag = tag;
  }

	@Override
  public String getValue() {
    return this.value;
  }

	@Override
  public void setValue(String value) {
    this.value = value;
  }

  public String getUnits() {
    return this.units;
  }

  public void setUnits(String units) {
    this.units = units;
  }

	@Override
	public int compareTo(StudyAttribute t) {
		return this.tag.compareTo(t.tag);
	}

	@Override
	public String getUnit() {
		return this.getUnits();
	}

	@Override
	public void setUnit(String unit) {
		this.setUnits(unit);
	}

	@Override
	public boolean equals(Object obj) {
		if(obj instanceof StudyAttribute == false)
			return false;
		if(obj == this)
			return true;
		StudyAttribute rhs = (StudyAttribute) obj;
		return new EqualsBuilder().appendSuper(super.equals(obj)).append(tag, rhs.tag).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(17,37).append(tag).toHashCode();
	}
}
