# HTTP
http:
  rootPath: "/api/*"
  port: 8998

# ElasticSearch index and hosts
elastic:
  indexName: "dcc-release-r--dev-06d-6-24"
#  indexName: "dcc-release-r--dev-06d-6-20"
#  indexName: "dcc-release-release5"

  nodeAddresses:
    - host: "10.0.20.213"
      port: 9300
    - host: "10.0.20.214"
      port: 9300

# Genomemaps
browser:
  dataSources:
     - uri: gene
       className: org.icgc.dcc.portal.browser.ds.GeneDataSource
     - uri: mutation
       className: org.icgc.dcc.portal.browser.ds.MutationDataSource

# Data download
download:
  enabled: true
  uri: "hdfs://hcn50.res.oicr.on.ca:8020"
  dynamicRootPath: "/icgc/download/dynamic/r12"
  staticRootPath: "/icgc/download/static"
  currentReleaseSymlink: "/current /r12"
  maxUsers: 20
  stage: "DEVELOPMENT"

# Logging settings
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL
  level: INFO

  # Logger-specific levels
  loggers:

    # Very chatty
    "com.wordnik.swagger.jsonschema.ApiModelParser": WARN

    # ERRORs should be converted to WARNs in Swagger 1.2.2
    "com.wordnik.swagger.jaxrs.HelpApi": OFF

